xing/hops

etc/webpack.base.js
lib/config.js
package.json

This pr gets rid of the direct dependency to "normalize.css" and instead makes this part configurable by the application.
Simply pass the dependencies as an array in `.hopsrc.js`, key: `cssAdditionalEntry`, default: `[]`

make css entries configurable

---

bin/setup.js
lib/config.js
package.json
readme.md

Adds a postinstall script which will try to create some boilerplate, so you can easily
do something like:
```sh
mkdir my-app && cd my-app
npm init && npm i hops -SE
npm start
```
And just have it work.

Adds postinstall script

---

etc/webpack.base.js
lib/config.js
lib/node.js
lib/prerender.js
lib/template.html

This pr enables the hops config to hand over an external service worker to the hops app.
Config values:
`serviceWorker`: Url to use (e.g. `/my-shared-assets/sw.js`) = possibly not part of the project (centralized asset server path) - if `null` (default), no serviceworker is included
`serviceWorkerFile`: Optional - a service worker can be part of the project. In this case, you can point this config to a js file, which is copied to `/dist/{serviceWorker}` in the prerender step. (So this config depends on the serviceWorker config)
Addition:
We restricted the delivery of a service worker to production mode (see https://github.com/xing/hops/pull/6/commits/77e7333c1a5f123d4dfa4e17f2f20fc67a86ff75). Service Workers are not really suitable for HMR and other dev features.

Include external serviceworker

---

lib/store.js

Redux DevTools was not being able to access the store because we needed
to set it up. This closes #7.

Enables Redux DevTools Chrome extension

---

.gitignore
app/.gitignore
app/README.md
app/jsdoc.json
app/package.json
app/src/main.js
bin/setup.js
jsdoc.json
lib/browser.js
lib/defaults.js
lib/node.js
lib/store.js
package.json
plugin/index.js
readme.md

rebased version of `feature/documentation`
adds dependencies
* jsdoc (forked version by @pixelass )
* hopsdoc (jsdoc theme)
adds documentation for the main app and defines documentation format.
The documentation needs to be reviewed.
When merged this can merged to `gh-pages` to update the online documentation

Add jsdoc & documentation

---

etc/webpack.base.js

`Configuration._raw` always delivered the whole config and therefore worked more or less exactly like `extract()`. But the intention was to expose only the part that was merged into - the delta. 
Addition: `removePlugin()`didn't work as expected --> switched to a String comparison.

Config: applies _raw as intended

---

lib/node.js

We just spend an hour search for the any hint where the build fails. This console.log statement will at least show the "location" which failed. 
Note, that the stacktrace by itself is not really helpful:
HOPS PLUGIN ERROR - rendering location /xing/malt-svg failed: 
TypeError: Cannot read property 'hash' of undefined
at Constructor.getInitialState (/Users/frederik.dietz/git/malt/public/bundle.js:14383:37)
at new Constructor (/Users/frederik.dietz/git/malt/node_modules/react/lib/ReactClass.js:668:54)

Output which location rendering failed

---

lib/node.js
plugin/index.js

Before the actual error was swallowed!
Example output:
[HOPS PLUGIN ERROR]: { ReferenceError: ejs:15
13|     <div id="__ROOT"><%- dom %></div>
14|     <script>
>> 15|       API_CACHE = <%- JSON.stringify(initialData) %>;
16|       MALT_CONFIG = <%- JSON.stringify(maltConfig) %>;
17|     </script>
18|     <%-js.map(function (path) {
initialData is not defined
at eval (eval at compile (/Users/frederik.dietz/git/test/malt-test/node_modules/ejs/lib/ejs.js:491:12), <anonymous>:20:31)
at returnedFn (/Users/frederik.dietz/git/test/malt-test/node_modules/ejs/lib/ejs.js:520:17)
at /Users/frederik.dietz/git/test/malt-test/node_modules/hops/plugin/index.js:126:24

show actual error with stack trace

---

etc/webpack.test.js

Hi all,
Webpack doesn't allow omitting the '-loader' suffix any more:
https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.26
Line 4 is still ok, since the removeLoader function uses regex to regard the suffix if present

Avoid BREAKING CHANGE by adding loader suffix

---

packages/config/configs/develop.js

This PR introduces a flag to webpack-dev-server which disables host checks and therefore allows running the server on 0.0.0.0 and bein reachable under localhost or other synonyms.
This is needed to open pages in a vm.

feat(hops-config): disable host check

---

package.json
spec/codestyle.js

This commit switches the parser of "semistandard" to "babel-eslint" in
order to enable semistandard to correctly parse files that contain flow
type annotations.
It also enables the "eslint-plugin-flowtype" as is recommened in the
semistandard documentation:
https://github.com/standard/standard#can-i-use-a-javascript-language-variant-like-flow-or-typescript

(1/4) chore: semistandard uses parser "babel-eslint" to recognize flowtype

---

packages/config/sections/module-rules/babel.js
packages/config/sections/module-rules/file.js
packages/config/sections/module-rules/json.js
packages/config/sections/module-rules/postcss.js
packages/config/sections/module-rules/url.js

to fix the issue with packages not being installed in root node_modules in newer yarn versions.
https://github.com/yarnpkg/yarn/issues/4394
Got this error in a hops-powered project.
```
hops server listening at http://0.0.0.0:8080
ERROR in multi webpack-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./node_modules/hops-config/shims/develop.js
Module not found: Error: Can't resolve 'babel-loader' in '/Users/robin.drexler/Development/malt'
@ multi webpack-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./node_modules/hops-config/shims/develop.js
```
create-react-app also does this: https://github.com/facebookincubator/create-react-app/blob/6644054fc3f64533dd1b9469baa2fab94e44b721/packages/react-scripts/config/webpack.config.dev.js

fix(hops-config): use hops relative loader packages

---

packages/config/lib/parse-env.js

`isArrayIsh` incorrectly detected empty objects `{}` as being an array.
With this fix it will no longer return true for these cases.

fix(config): incorrect detection of empty objects as being an array

---

packages/config/index.js

In case that the hops user configuration is not set in the npm
environment (for example by starting a service without npm script).
`hops-config` will try to read the config section of the package.json
to read the config.

feat(config): read hops user config from package.json if not in env

---

packages/react/readme.md
packages/redux/readme.md

The package `hops-react` has a peerDependency to `hops-config` but it
isn't specified in the package's `readme.md` installation instructions.
The package `hops-redux` has a peerDependency to `react` but it isn't
specified in the package's `readme.md` installation instructions.
This PR adds the missing peerDependencies to the installation
instructions in both readme files.

docs: add missing peerDependencies to hops-react/redux readme example

---

packages/jest-preset/package.json

In favor of #227 
Thanks @dmbch :)

fix(jest-preset-hops): add babel-core to satisfy peer dependencies

---

packages/config/configs/develop.js

In two demo projects, I was able to cut incremental build time in half.
It's also the setting, the [webpack docs recommend](https://webpack.js.org/guides/build-performance/#devtool) and is used by [preact-cli](https://github.com/developit/preact-cli/blob/8a2dfffa832c1ac6c7ca535baf0a2500a7799448/src/lib/webpack/webpack-base-config.js#L228).

feat(hops-config): use faster source map strategy

---

packages/config/sections/module-rules/babel.js

to fix issues with babel plugin packages not being installed in root node_module
Similar to https://github.com/xing/hops/pull/214

fix(hops-config): use hops relative babel plugins packages

---

packages/build-config/README.md
packages/build/README.md
packages/cli/README.md
packages/config/README.md
packages/express/README.md
packages/jest-preset/README.md
packages/local-cli/README.md
packages/middleware/README.md
packages/plugin/README.md
packages/react/README.md
packages/redux/README.md
packages/renderer/README.md
packages/server/README.md
packages/spec/README.md
packages/template-minimal/README.md
packages/template-react/README.md
packages/transpiler/README.md

No nice blue badges (or npm links) are there in all those READMEs
Use small badges or shields provided by https://shields.io to display npm versions in READMEs and link to the respective npm project page

docs(*): add npm version shields to READMEs

---

packages/jest-preset/README.md

- Url to jest docs is broken  (404)
- Preset name in the example is wrong.
- fixed url
- fixed preset name

docs(jest-preset-hops): fixed README.md jest docs url and example

---

packages/build-config/configs/build.js
packages/build-config/configs/develop.js
packages/build-config/configs/node.js
packages/express/app.js
packages/local-cli/commands/build.js
packages/local-cli/commands/develop.js
packages/local-cli/commands/serve.js
packages/local-cli/commands/start.js

NODE_ENV is accepted as a global variable and therefore is used for code optimizations in the minifying step. But we also need it for a global variable called HOPS_MODE, which indicates whether the application runs in a `static` build environment or a `dynamic` middleware use case.
Added the environment variable `HOPS_MODE` with a default of `dynamic` to all webpack configs.

feat(build-config): added mode as environment variable

---

packages/local-cli/package.json

`hops-global-cli init` fails with `Error: Cannot find module 'hops-config'` due to missing `hops-config-dependency`

fix(hops-local-cli): add missing hops-config dependency

---

lerna.json

Because of a bug in lerna the registry environment variable will be set
to yarnpkg in certain cases, therefore we specify the registry manually
in the lerna config.
Related: https://github.com/lerna/lerna/issues/896

chore: specify npm registry in lerna config

---

packages/graphql/node.js
packages/react/dom.js
packages/react/node.js

The last hops update changed the behaviour of the main render method(s).
This PR restores the previous behaviour, while introducing another render context life cycle method, `prepareEnhancedElement`.

Fix render context life cycle

---

packages/express/README.md
packages/express/index.js

`startServer` was renamed to `runServer` without flagging a breaking change.
Re-introduce `startServer` export.

Fix express export

---

packages/graphql/package.json

hops-graphql is currently completely broken because its `lib` folder is missing.
`lib` folder is included in npm package.

fix(graphql): add lib folder to package

---

packages/express/index.js

`runServer` added a new `options` argument startServer didn't require.
Make `runServer` compatible again.

fix(express): fix startServer method signature

---

packages/redux/index.js

not passing options.reducers causes an error, [which it did not before](https://github.com/xing/hops/commit/f11cac86c9f98733588482053c26d0d2ab8e1c46#diff-6163e5b6f61632ddf858987872971110L15).

fix(hops-redux): make options.reducers optional again

---

package.json
packages/build/server.js

This pull request closes issue #266 
In the server.js:
https://github.com/xing/hops/blob/v7.4.0/packages/build/server.js#L22
currently, after the devServer config options there is an additional object (the one with the after function and the watchOptions). This way, it is impossible to override that functionality. For example, you are always stuck with the rewrite:
https://github.com/xing/hops/blob/v7.4.0/packages/build/server.js#L24
even if you don't want to use that.
This change simply changes the order here:
https://github.com/xing/hops/blob/v7.4.0/packages/build/server.js#L22
from:
Object.assign({}, config.devServer, { after: .... })
to:
Object.assign({}, { after: .... }, config.devServer)
So now the devServer configs can override even the 'after' function and the watchOptions, if it …

Give devServer config higher priority

---

packages/build/build.js
packages/plugin/index.js
packages/renderer/index.js
packages/spec/plugin.js
packages/spec/renderer.js

Static renderer does not apply bootstrapServer function from hops-config. In this regard, its implementation differs from our servers.
Renderer now applies the `bootstrapServer` function, aligning it with server behaviour. It does so by actually instantiating an [Express Router](http://expressjs.com/en/4x/api.html#router) and using it for rendering.
N.B.: I deliberately decided to not also apply `teardownServer`, because the primary use-case of that function is to set up error handling and logging. We are doing both ourselves in a static rendering context.

Improved renderer

---

packages/build-config/configs/build.js
packages/build-config/package.json
yarn.lock

No sourcemaps and stats written.
Sourcemaps and stats are written in order to allow consumers to analyze their bundles. 
Sourcemaps also allow for debugging in production.

Add sourcemap and build stats

---

packages/graphql/lib/util.js
packages/graphql/node.js

`fs.existsSync` checks on every request.
Check on server startup.

perf(graphql): remove fs.existsSync() check from context

---

packages/react/node.js
packages/spec/serve.js

Miss/Status components in hops-react are broken.
Due to the recent changes, the router's static context was lost - this is now fixed: routerContext is now returned as a part of templateData.
With this PR, we also make sure Helmet.renderStatic() is being called for every request, preventing an eventual memleak.

fix(react): re-enable Miss/Status components

---

packages/graphql/dom.js
packages/graphql/node.js
packages/react/dom.js
packages/react/node.js
packages/react/package.json
packages/redux/index.js
yarn.lock

We are using object literals (with constructor props) as context definitions.
Context definitions are now constructor functions with prototypes, enabling us to leverage standard (`class`) inheritance.

Context constructors

---

packages/redux/README.md
packages/redux/index.js
packages/spec/redux.js

In order to set redux middlewares a consumer needs to create a new context that mixes with the redux context and override `getMiddlewares`.
Since it's a pretty common use case to set middlewares, make it easier to do so by adding it as a context option.

Redux middleware option

---

packages/graphql/dom.js
packages/graphql/node.js
packages/react/dom.js
packages/react/node.js
packages/redux/index.js

Currently, hops-{react,redux,graphql} export their respective context definitions as `contextDefinition`. As these exports tend to be extended by downstream projects, they provide a somewhat un-idiomatic usage:
```javascript
import { contextDefinition } from 'hops-react'
class MyContext extends contextDefinition {...}
```
We now also have a proper constructor export:
```javascript
import { ReactContext } from 'hops-react'
class MyContext extends ReactContext {...}
```

Additional context exports

---

packages/react/node.js
packages/react/package.json
yarn.lock

Currently, cloned context mixins have to take care of merging options.
With the proposed change, context mixin constructors receive a single merged options hash.

Context cloning

---

packages/lambda/deploy.js
packages/lambda/lib/aws-config.js
packages/lambda/lib/create-lambda-bundle.js
packages/lambda/package.json
yarn.lock

This commit changes the way we zip the lambda bundle.
Before: We were only zipping the production dependencies,
build artifacts and package.json file.
After: Now we zip the entire project directory (excluding node_modules)
and then selectively adding production dependencies.
We now also have configurable include/exclude glob patterns.

feat(lambda): include entire project dir in zip file (minus dev deps)

---

packages/react/README.md
packages/react/dom.js
packages/react/node.js

Currently, users have to provide their own (derived) `ReactContext` implementation if they want to pass props to ReactRouter instances.
With this PR, we introduce a router config option allowing users to pass in ReactRouter props. Primary use-case is implementing a custom [`getUserConfirmation` function](https://reacttraining.com/react-router/web/api/BrowserRouter/getUserConfirmation-func).

Configurable router

---

package.json
packages/build/build.js
packages/build/lib/generate.js
packages/build/package.json
packages/express/app.js
packages/express/commands/serve.js
packages/express/index.js
packages/plugin/README.md
packages/plugin/index.js
packages/renderer/README.md
packages/renderer/index.js
packages/renderer/package.json
packages/spec/renderer.js
yarn.lock

Using our custom Webpack plugin, we are currently running Webpack within Webpack. That's probably not the simplest way to achieve what we want.
Get rid of custom Webpack plugin.

Deprecate plugin, refactor

---

package.json
packages/build-config/README.md

The example in the build-config readme is wrong. 
The example in the readme is updated. 
Closes #296

docs(build-config): fix wrong import in example

---

README.md

Project templates are missing in main README.
Now, they are mentioned.

docs: mention templates in main README

---

packages/server/index.js

This commit ensures that the path rewrite mechanism `rewritePath` is
only executed when a hops build happens in static mode (app shells).

fix(server): only rewrite path if run in static mode

---

packages/cli/hops.js
packages/cli/package.json

Previously the `hops-cli` package could only be executed in the root
directory of a hops project.
With this change it will be possible to execute the hops cli from any
folder inside a hops project.

refactor(cli): allow cli to be executed anywhere inside hops project

---

.travis.yml
package.json
packages/spec/redux.js

Before:
eslint had to be executed manually via (`yarn lint`) and PRs with
linting issues were shown as "passing" - where they should have
failed.
After:
eslint is executed after the tests on every travis run.

chore: make sure eslint is executed on travis

---

packages/build-config/configs/build.js

Generated stats.json includes manifest chunk, which does not exist, because the write-file plugin removes it. (while writing its content into the hops cache folder).
Tools, such as `webpack-bundle-analyzer` had issues parsing the stats.json file
```
Couldn't parse bundle asset "/Users/robin/beep/boop/manifest-test/build/manifest.js".
Analyzer will use module sizes from stats file.
```
- Remove superflous `manifest.js.map` file
- Register `StatsWriterPlugin` after `WriteFilePlugin`

Fix stats.json including manifest chunk, which does not exist 

---

packages/cli/README.md
packages/local-cli/README.md

This is in preparation for #315 
It should be merged first, then released to npm and immediately after that the PR #315 should be merged and released to npm.

(1/2) deprecate hops-cli and hops-local-cli

---

packages/cli/hops.js
packages/cli/package.json

Requiring a local package in a global scope (CLI) might break, if that
local package requires other local packages, because then
`require.resolve` will try to resolve against the global scope.
In this case we needed `hops-config` only to get the application root,
which we now find ourselves by using `pkg-dir`.

fix(cli): do not require local packages in global context

---

packages/jest-preset/package.json
yarn.lock

[jest 22 has been released](https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-2200). Tested jest@22 with the hops default template. `jest-preset-hops` still seems to work, so I'd like to increase the range of supported jest versions. :)

feat(jest-preset-hops): add jest 22 to peerDependency range

---

packages/cli/lib/commands.js

The CLI package still needed `hops-config` (which has been removed in a previous commit.
This PR fixes that by replacing `hopsConfig.appDir` with `pkg-dir` in the `lib/commands.js` script.

fix(cli): re-add accidentally removed hops-config dependency

---

packages/lambda/package.json

Specify peerDependencies also in devDependencies in order to have lerna
take care of updating the version numbers.

fix(lambda): specify peerDependencies also in devDependencies

---

package.json
packages/spec/package.json
yarn.lock

There is no automated way to publish major releases, as we need to force publishing to ensure the major version of all packages is consistent. Also, some `package.json`s need cleanup.
We now have a `release:major` script.

Tweak manifests

---

packages/cli/init.js

Templates can't provide .npmrc file, because they're ignored by `npm pack`.
Templates can provide a .npmrc file by adding a _npmrc file.
This works identically to what we are [already doing for .gitignore files](https://github.com/xing/hops/blob/master/packages/cli/init.js#L84).
[There are plenty of other files that are ignored by default when publishing a package](https://github.com/npm/npm/blob/219589aa4e5f8cac6d42c09311857440a0c18651/doc/misc/npm-developers.md#keeping-files-out-of-your-package), but I'm certain we don't need any more of them. Hence I went with an additional if instead of adding a more generic solution.

fix(hops-cli): allow to add .npmrc in templates

---

packages/middleware/README.md
packages/renderer/README.md

Currently, the example code on some READMEs use previous API versions and are therefore broken.
Example code is fixed.

Fix Readmes

---

packages/cli/README.md
packages/cli/commands/start.js
packages/graphql/commands/graphql.js

Hops CLI's `start` command does not perform a build in production mode.
In production mode, if hops-build is installed, a full build is executed when starting the server. This behaviour can be deactivated by passing '--clean=false'.

Improve CLI

---

packages/build-config/configs/node.js

This pull request closes issue #342
Previously, most of `node_modules` was excluded from bundling in Node.js builds. Unfortunately, this also prevented CSS files (and other file types) from being imported.
This commit adds an RegExp check to make sure we bundle all file types except JSON and JS.

Fix CSS Imports

---

packages/react/README.md
packages/react/lib/components.js
packages/react/node.js

No way to set http headers from inside the application.
This is useful for example to set (surrogate) cache headers or to set cookies. 
Header component is added to allow setting http headers
**Needs tests.**

Add Header component to allow setting http headers declaratively

---

packages/graphql/node.js

This pull request closes issue #324 
Currently, GraphQL data is always being prefetched, even in static rendering mode.
In static mode, during server side rendering, GraphQL data is no longer being prefetched. That appears to be the sane default. The old behaviour can be restored by extending `GraphQLContext` and overriding its 'prefetchData' method.

Disable GraphQL Data Fetching in Static Mode

---

.gitignore
packages/graphql/dom.js
packages/graphql/node.js
packages/react/README.md
packages/react/dom.js
packages/react/lib/common.js
packages/react/node.js
packages/react/package.json
packages/redux/index.js
packages/template-graphql/src/app.js
packages/template-react/src/app.js
yarn.lock

**Proposal for a simplified alternative to the existing react based rendering.**
Objective: hide context (a truly advanced feature) from the react developer
Instead of passing a context to render, you can now pass a configuration object that also describes which additional rendering features you need, like:
```javascript
import { reduxExtension } from 'hops-redux';
export default render(<App />, {
extensions: [reduxExtension({ reducers })],
});
```
Each react based package now exports itself as an extension.
**This is a non-breaking change, if you want to you can still pass a context.**

feat(react): render variant hiding contexts from users

---

packages/config/README.md
packages/config/index.js

Placeholders (`<placeholder>`) can only be used in filesystem related config properties.
Placeholders can be used in all kinds of config properties to reference other values. For example, assuming your `basePath` is `/`, `<basePath>/foo` will be resolved to `/foo`.

Placeholders Everywhere

---

package.json

Developers try to install packages using npm, running into all sorts of issues since we are using yarn workspaces which are not supported by npm.
Added hook to ensure installation fails when trying to use npm

chore: fail install when npm is used

---

packages/config/index.js

`extends` is currently completely broken, as the default values always take precedence.
Default values are now mixed in after all other config override mechanisms habe been applied.

Fix Config Extension Mechanism

---

package.json
yarn.lock

We recently accidentally added a `.only` to a mocha describe block, potentially causing false positive ci runs.
To avoid that in the future this PR adds a linting rule that fails when a .only is found in a test.

chore: add no-only lint rule for mocha to avoid false positive ci runs

---

packages/build/build.js

Some errors don't have a "stack" property, which would lead to a
TypeError when trying to log the original error.
Now all errors are printed, with or without stack.

fix(build): log errors without "stack" instead of swallowing them

---

packages/middleware/README.md
packages/renderer/README.md

This PR adds deprecation notices to the READMEs of
hops-middleware and hops-renderer and should be merged and released
separately of the actual removal PR.

(1/2) Deprecate hops-middleware and hops-renderer

---

packages/lambda/README.md
packages/lambda/lib/aws-config.js

This commit changes the lambda configuration to use the key `_aws`
instead of `aws` which means the aws config will not be included in
the client-side JS bundle.
If `hopsConfig._aws` is not found it falls back to `hopsConfig.aws` to
ensure that this is a non-breaking backwards-compatible change.
Fixes: #319

feat(lambda): hide aws configuration from browser by prefixing with _

---

.prettierignore
package.json

eslint does not lint *.{json,css,md} files and therefore does not catch
differences in prettier formatting in these files.
~This commit adds a separate command that executes "prettier -l" to list
the differences in the above mentioned files and fails the "lint"
script if there are any differences reported~
We are now excluding `**/package.json` files from prettier formatting.

chore: exclude **/package.json files from prettier formatting

---

packages/express/lib/app.js
packages/express/package.json
yarn.lock

This PR adds gzip compression to the express server.
~WIP because it needs investigation how Lambda / API Gateway behave when
they deal with gzip compressed responses.~
API Gateway expects Lambda to return compressed responses in order to serve compressed responses to the client.

feat(express): enable gzip compression

---

packages/lambda/lambda.js

This fixes an issue we had with our internal deployment where a proxy
would be used in front of Lambda, which broke when basePath was set to
'/'.

refactor(lambda): only rewrite request when basePath contains stage

---

packages/spec/config.js
packages/spec/mock/config/nested-extends/package.json

When executing tests from the workspace root directly (through
`./node_modules/.bin/mocha 'packages/spec/*.js'`) the config tests will
not be able to resolve to the correct mock directories because at the
moment they were using `path.resolve` which resolves from the current
working directory.
By using `__dirname` we can circumvent this issue and make the tests
more robust.

test: make paths in config unit tests more robust by using __dirname

---

packages/build/lib/renderer.js

Static builds due not work, because the server timings middleware is not applied in the renderer. 
```
$ hops build --static
TypeError: Cannot read property 'start' of undefined
at /Users/robin.drexler/Development/_hops/packages/react/node.js:73:1
at /Users/robin.drexler/Development/_hops/packages/build/lib/middleware.js:42:9
at <anonymous>
✨  Done in 6.31s.
```
Server timings middleware is not applied in the renderer, fixing the issue. 
I will provide tests for that, after #436 is merged.

fix(renderer): fix static build not working due to missing res.locals.timing

---

packages/build/commands/build.js

Bug noticed earlier today by a co-worker (can't find his github handle :(), will attribute later.
If `hops-build` fails, it still exits with exitCode 0.
After this PR, `hops-build` will exit with exitCode 1 for webpack errors, build errors and build warnings. I guess it is fair to fail on warnings in a production build.
https://github.com/webpack/docs/wiki/node.js-api#error-handling

fix(build): exit with exitCode 1 when build fails

---

packages/build/commands/build.js

Breaking the webpack build on webpack warnings seems a little too
restrictive.
For example the performance hints are logged as warnings and therefore
break the build.
After this change the build will only exit with an error code of 1, if
the build contains errors, but not if the build only contains warnings.

fix(build): do not break build on webpack warnings

---

packages/react/lib/common.js

Currently, if you do not pass any options (i.e. extensions) to render, the following error is thrown:
`TypeError: Cannot read property extensions of undefined`
This PR makes options an object by default, preventing the error

fix(react): do not throw error when no options are passed in render

---

packages/config/__tests__/config.spec.js
packages/config/index.js
packages/express/lib/utils.js

- hops-config reads port from `process.env.PORT` and defaults to `undefined`
- hops-express reads port from hops-config:
- if port is undefined it starts at 8080 and tries to find the next free port
- if port has a value it uses that port and does not try to find a free port

choose next free port

---

packages/graphql/package.json
packages/lambda/package.json
packages/react/package.json
packages/redux/package.json
packages/spec/package.json
yarn.lock

This fixes a couple of our peerDependency warnings.
Not sure why it doesn't fix everything - I suspect that some packages
are being pulled from the registry instead of taken from the monorepo,
but can't verify this until we have published a new version of hops.

chore: fix peer dependency warnings

---

packages/build-config/configs/node.js

Due to [webpack defaults](https://github.com/webpack/webpack/blob/1313300b52d933dc4519ee70142db8e9ad3eecd8/lib/WebpackOptionsDefaulter.js#L272) uglify is used to minify server-side code, resulting in longer build times and errors.
Default is overridden so that no uglify is used for server build.

chore(build-config): override minimizer defaults to not use uglify for node build

---

packages/express/lib/utils.js

with the new webpack entrypoint API the hot-update.js chunk will also be
included as entrypoint and therefore will be loaded as script tag in our
HTML template.
This breaks when we load the scripts with the "async" attribute set:
`Uncaught ReferenceError: webpackHotUpdate is not defined`.
This commit is a quick fix to restore the previous behaviour where we
will not include the hot-update.js chunk as a script in our template.
Other possible fixes:
- Enable `multiStep` in HotModuleReplacementPlugin
- Load all scripts sync or in order (defer instead of async)

fix(express): exclude hot-update.js from being added as script tag

---

packages/build-config/configs/build.js

for example keyframes in different chunks got the same name, causing all sorts of issues

fix(build-config): Do not use optimizations that assume concatenation

---

packages/build-config/configs/build.js

There are occasions where the css optimizer plugin would remove prefixes that should not be
removed. This might be caused by the plugin using an older cssnano and autoprefixer version
Since we already deal with prefixes at other points in the config, we remove it here to be safe

fix(build): fix prefixes in dev and prod being different

---

packages/graphql/README.md
packages/graphql/mixin.browser.js
packages/graphql/mixin.server.js
packages/graphql/package.json
packages/redux/README.md
packages/redux/mixin.browser.js
packages/redux/mixin.server.js

For some use cases, we need to be able to inject a request-aware fetch implementation.
For redux, we'd like to be able to override the thunk middleware to use [extraArguments](https://github.com/reduxjs/redux-thunk#injecting-a-custom-argument).
In Apollo, we'll inject a custom fetch into the `ApolloLink`.
This PR adds hook that'll enable such efforts.

add hooks to allow overriding of data fetching

---

packages/development-proxy/README.md
packages/development-proxy/mixin.core.js
packages/development-proxy/package.json
packages/development-proxy/preset.js
packages/spec/helpers/env.js
packages/spec/integration/development-proxy/__tests__/object-config.js
packages/spec/integration/development-proxy/__tests__/string-config.js
packages/spec/integration/development-proxy/browser.js
packages/spec/integration/development-proxy/mixin.core.js
packages/spec/integration/development-proxy/package.json
packages/spec/integration/development-proxy/server.js
yarn.lock

Add a simple proxy for API requests which runs on the same port as the app, mitigating issues with CORS.
Inspired by cra proxy.
Configuration is meant to be simple and limited. For more sophisticated use cases it is probably more feasible to build a custom mixin.
Can be configured in two ways in preset config.
`proxy` string: In this case all<sup>[1]</sup>requests will be proxied to the specified proxy URL.
[1] All meaning every request that is not handled by the webpack dev middleware and that is not a requested html document. Those are handled by the app itself.
```json
{
"hops": {
"proxy": "https://example.org"
}
}
```
or with env var:
```json
{
"hops": {
"proxy": "[PROXY_URL]"
}
}
```
`proxy` can also be an object.
```json
{
"hops": {
"proxy": {
"/foo": { "target": …
```

feat(development-proxy): add development proxy

---

packages/graphql/README.md
packages/graphql/mixin.browser.js
packages/graphql/mixin.server.js
packages/react/README.md
packages/react/fetch/mixin.runtime.js
packages/react/package.json
packages/react/preset.js
packages/redux/README.md
packages/redux/mixin.browser.js
packages/redux/mixin.server.js

Why the move to react?
- with the introduction of `fetch` in addition to `configureFetch`, we are able to access the fetch without having to pass a default implementation every time when calling `configureFetch`
- moving it to react will allow us to easily add hoc and context for fetch, so it can be used inside the app, too

Fix configure fetch

---

packages/lambda/lambda.js

_This is a template. Feel free to remove the parts you do not need! Start with this line, for example_ :wink:

refactor(lambda): use NODE_ENV instead of CLI args to start prod mode

---

packages/graphql/lib/fragments.js

Some GraphQL server requires a operation name (operation name is mandatory).
Add operation name to introspection query for compatibility reasons.

fix(graphql): operation name support in introspection query

---

packages/postcss/mixin.core.js

Because this creates a lot of duplication when importing css variables
files in other css files which are then imported via js.
See:
- https://github.com/postcss/postcss-import/issues/316
- https://github.com/postcss/postcss-import/issues/294
- https://github.com/postcss/postcss-import/issues/224

fix(postcss): do not output custom properties in resulting css

---

packages/spec/helpers/env.js
packages/spec/helpers/test-helpers.js

Sometimes the integration tests just hang and it is hard to see why.
With this change we use the "debug" module to output "hops-spec:*" debug
messages which can be printed to the terminal when setting the
`DEBUG` environment variable to: `DEBUG=hops-spec:*`.
In order to still allow to debug puppeteer visually (starting it in
non-headless mode) we changed the environment variable name from:
`DEBUG=true` to `DEBUG_PUPPETEER=true` in order to not interfere with
the actual debug output.

feat(spec): add debug output for integration tests

---

packages/redux/action-creator-dispatcher/mixin.server.js

mixins often use bootstrap for setup as it is the only place with access to req and res
when hooks of those mixins are called in bootstrap before their bootstrap hook ran, bugs are often the result

fix(redux): Do not dispatch actions in bootstrap hook to avoid clashes

---

packages/spec/helpers/test-helpers.js
packages/spec/package.json
yarn.lock

This pull request closes issue #594.

fix(test): Replace `ncp` with `fs-extra` package to prevent test runner from getting stuck

---

.travis.yml

Sometimes travis uses an older Node 8 version (8.9 for example) which
will break the build because the "engines" field in Hops is set to
">= 8.10".
This commit ensures that travis will always use Node 8.10

chore: ensure that travis always uses Node 8.10 to run tests

---

packages/jest-preset/jest-preset.js
packages/jest-preset/package.json
packages/jest-preset/transforms/babel.js
packages/spec/integration/jest-preset/tsconfig.json
packages/spec/integration/typescript/package.json
packages/typescript/README.md
packages/typescript/mixin.core.js
packages/typescript/package.json
packages/typescript/tsconfig.json
yarn.lock

Due to several issues with the new @babel/preset-typescript we decided
to revert back to using typescript itself:
https://github.com/xing/hops/pull/613#issuecomment-418701043

Revert @babel/preset-typescript to use ts-loader and typescript

---

packages/graphql/mixin.browser.js
packages/graphql/mixin.server.js

This pull request closes issue #619
We had a bug in our GraphQL mixin that prevented us from overriding the
exposed `getApolloLink` mixin hook.
The problem was that we called mixin methods inside the constructor, but
at that time the mixin container has not been created, so when some
other mixin tries to override the mixin method it will never be called.
Also while working on this problem I found out that our introspection
results are never actually used, because a new instance is created for
each request and therefore `this.introspectionResult` was always set to
`undefined`.
I moved the instantiation of the apollo client from the constructor to
the `bootstrap` method in order to allow for `getApolloLink` to use an
overridden implementation.
I also moved the fragment types reading / …

Fix GraphQL mixin and fragment type caching

---

packages/graphql/README.md
packages/graphql/mixin.browser.js
packages/graphql/mixin.server.js

To be consistent with `getApolloLink`.
Also now calls the hook even if option.link is set. The hook now gets to decide whether to respect the options or ignore it.

feat(graphql): Introduce getApolloCache hook

---

.travis.yml

- enables caching
- sets max worker threads for jest to 2
- clone only last 3 commits
- install up-to-date yarn

chore: make travis a little bit faster

---

packages/lambda/lib/aws-config.js

`hops-lambda` does not include the `server.js` in its zip bundle.
`hops-lambda` now always includes the `config.serverDir` in its zip
bundle.

fix(lambda): always include serverDir in bundle

---

packages/graphql/mock-server/README.md
packages/graphql/mock-server/mixin.core.js

affects: hops-graphql
graphql mock server requests are answered with invalid CORS headers
leverage CORS config options in apollo middleware / server and configure them correctly

fix: correct CORS headers for graphql mock server

---

README.md
packages/cli/commands/hops.js
packages/cli/lib/create-app.js
packages/create-hops-app/README.md
packages/create-hops-app/index.js
packages/create-hops-app/package.json
packages/spec/integration/create-hops-app/__tests__/index.spec.js
packages/spec/integration/create-hops-app/package.json
packages/spec/package.json

Add package to allow using `yarn create hops-app` to initialize a new hops application.
I moved the code from `hops` to this new package and would remove it from `hops` in an additional commit. Leaving the `hops` package as a local cli only.
Is that a direction you'd support @ZauberNerd @dmbch ?

add Create hops app package

---

packages/spec/integration/create-hops-app/__tests__/index.spec.js

Yarn and npm write information to stdout/stderr which will then show up
in the integration tests - this commit suppresses their output.

chore: silence stdio in create-hops-app integration tests

---

packages/react/package.json
packages/template-graphql/package.json
packages/template-react/package.json
packages/template-redux/package.json

The package react-router is a direct dependency of react-router-dom and
it is recommended to always import react-router-dom instead.

fix: remove superfluous react-router dependency

---

packages/pwa/lib/service-worker-plugin.js

The `hops-pwa` service worker plugin previously broke source maps for
the service worker file - this PR addresses this issue by using
`ConcatSource` instead of `RawSource` of `webpack-sources` which takes
care of keeping source maps intact.

Improve hops-pwa service-worker plugin

---

package.json
packages/spec/helpers/env.js
packages/spec/integration/create-hops-app/__tests__/index.spec.js
packages/spec/integration/create-hops-app/package.json
packages/spec/integration/development-proxy/__tests__/object-config.js
packages/spec/integration/development-proxy/__tests__/string-config.js
packages/spec/integration/development-proxy/package.json
packages/spec/integration/graphql-mock-server/__tests__/develop.js
packages/spec/integration/graphql-mock-server/package.json
packages/spec/integration/graphql/__tests__/develop.js
packages/spec/integration/graphql/package.json
packages/spec/integration/jest-preset/package.json
packages/spec/integration/lambda/__tests__/build.js
packages/spec/integration/lambda/package.json
packages/spec/integration/postcss/__tests__/build.js
packages/spec/integration/postcss/__tests__/develop.js
packages/spec/integration/postcss/package.json
packages/spec/integration/pwa/__tests__/build.js
packages/spec/integration/pwa/package.json
packages/spec/integration/react/__tests__/develop.js
packages/spec/integration/react/package.json
packages/spec/integration/redux/__tests__/develop.js
packages/spec/integration/redux/package.json
packages/spec/integration/styled-components/__tests__/develop.js
packages/spec/integration/styled-components/package.json
packages/spec/integration/typescript/__tests__/develop.js
packages/spec/integration/typescript/package.json
packages/spec/jest.setup.js

Our tests are sometimes failing with a jest timeout.
Therefore I have moved the timeout setup to a global
`setupTestFrameworkScriptFile` in which the timeout is set to 5 minutes.

test: set jest timeout globally to 5 minutes (for each file)

---

packages/cli/mixin.core.js

Since we don't break the build anymore when the build has warnings, we
now log errors and warnings during watch mode to the terminal.
We do however still reject the render middleware promise for errors, so
that express will then only render that error in case the build has any

feat(cli): log webpack errors and warnings in watch mode to terminal

---

packages/cli/package.json
packages/config/package.json
packages/lambda/lambda.js
packages/lambda/lib/aws-config.js
packages/lambda/package.json
packages/mixin/package.json
packages/postcss/mixin.core.js
packages/postcss/package.json
packages/preset-defaults/package.json
packages/pwa/mixin.core.js
packages/pwa/package.json
packages/react/package.json
packages/spec/integration/hot-module-reload/__tests__/develop.js
packages/spec/integration/hot-module-reload/index.js
packages/spec/integration/hot-module-reload/package.json
yarn.lock

Reload currently does not work after a file has been changed.
This PR will fix it with an untool upgrade after [this PR](https://github.com/untool/untool/pull/189) or another fix has been merged and released.
I've already written basic tests. The second one should immediately be green after the upgrade. (Tried it with modified node_modules folder)

Upgrade untool to fix HMR

---

packages/react/mixin.core.js
packages/react/package.json

We include `plugin-proposal-object-rest-spread`, although `syntax-object-rest-spread` is included in @babel/preset-env since v7.
https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/available-plugins.js#L3
Remove `plugin-proposal-object-rest-spread`.

chore(react): remove obsolete babel plugin

---

package.json

Before `lerna publish` would fail after publishing the packages with the
following message:
```
lerna ERR! Error: Command failed: git checkout -- spec//package.json
lerna ERR! error: pathspec 'spec//package.json' did not match any file(s) known to git
lerna ERR!
lerna ERR!     at makeError (./node_modules/@lerna/child-process/node_modules/execa/index.js:174:9)
lerna ERR!     at Promise.all.then.arr (./node_modules/@lerna/child-process/node_modules/execa/index.js:278:16)
lerna ERR! lerna Command failed: git checkout -- spec//package.json
lerna ERR! lerna error: pathspec 'spec//package.json' did not match any file(s) known to git
lerna ERR! lerna
error Command failed with exit code 1.
```
In order to avoid this problem we remove the trailing slash from the
`spec` workspace configuration …

chore: remove trailing slash from workspace to un-confuse lerna publish

---

packages/graphql/mixin.core.js

Using require.resolve enables to use mock files in other node packages easily
The current fs.existsSync check prevented that although it would actually already be possible
in the current implementation.

fix(graphql): align exists check and resolve algo for graphqlMockSchemaFile

---

packages/cli/lib/init.js
packages/cli/package.json
packages/config/package.json
packages/graphql/package.json
packages/lambda/package.json
packages/mixin/package.json
packages/preset-defaults/package.json
packages/pwa/package.json
packages/react/package.json
packages/spec/integration/postcss/__tests__/develop.js
packages/spec/package.json
yarn.lock

The latest puppeteer package breaks our tests. I've set the version to the latest working version (1.9.0) in the package.json.

chore: upgrade untool and other dependencies

---

packages/preset-defaults/README.md
packages/template-graphql/package.json
packages/template-react/package.json
packages/template-redux/package.json

Browserlist should be an array when passed as option to other tools. (like [autoprefixer](https://www.npmjs.com/package/autoprefixer#options)).
closes #694

Adjust browserlist to be an array

---

packages/styled-components/README.md

as the example is indeed below the text

docs(styled-components): change above to below

---

packages/graphql/README.md
packages/graphql/mixin.server.js
packages/graphql/preset.js
packages/redux/README.md
packages/redux/action-creator-dispatcher/mixin.server.js
packages/redux/preset.js

Instead of asking just one mixin whether it is ok to prefetch or not, we can now ask all relevant mixins and if at least one mixin disagrees we prevent prefetching.

replace shouldPrefetchOnServer with canPrefetchOnServer hook

---

packages/graphql/mixin.browser.js
packages/graphql/mixin.server.js

In some cases we may need to obtain information from the request,
response or other hooks through the "bootstrap" hook and want to use
that data during the instantiation of the apollo client.
At the moment the apollo client will be instantiated in the bootstrap
hook and therefore prevents us from using that scenario.
With this change we only instantiate the client at the last possible
time and therefore we can use the bootstrap and getApolloLink hooks to
overwrite them and inject additional data.
Example:
```javascript
class MyMixin extends Mixin {
bootstrap(req, res) {
this.language = res.locals.language;
}
getApolloLink() {
return new HttpLink({
uri: this.config.graphqlUri,
headers: {
'Accept-Language': this.language,
},
});
}
}
```

fix(graphql): lazily instantiate client to free up bootstrap hook

---

packages/create-hops-app/package.json

When you run the yarn create command, we propose in the readme:
```
yarn create hops-app@next --hops-version next --template hops-template-react@next my-awesome-project
```
you receive the following error:
```
success Installed "create-hops-app@11.0.0-rc.46" with binaries:
- create-hops-app
/bin/sh: /usr/local/bin/create-hops-app@next: No such file or directory
error Command failed.
Exit code: 127
Command: /usr/local/bin/create-hops-app@next
Arguments: --hops-version next --template hops-template-react@next my-awesome-project
Directory: /Users/robin/Development
```
yarn create usually works by installing the `create-something` package and then invoking the eponymous binary. 
In our case, it tries to find the `create-hops-app@next` binary, which obviously does not exist.
This seems to be a …

fix(create-hops-app): make yarn create work with @next tagged version

---

packages/react/index.js

Because support for the browser and server entrypoints in package.json
is still not standardized. E. g. Jest does not support them by default.

fix(react): deep import react runtime components from @untool/react

---

packages/styled-components/mixin.core.js

See: https://www.styled-components.com/docs/tooling#dead-code-elimination
Seems like something we can safely activate, doesn't it?

feat(styled-components): enable dead code elimination

---

packages/react/index.js
packages/spec/integration/react/index.js

React features like [`Component.contextType`](https://reactjs.org/docs/context.html\#classcontexttype)
and [`useContext`](https://reactjs.org/docs/hooks-reference.html\#usecontext) need the entire Context object to work
This is technically a breaking change, but it seems we're the only ones using the Consumer yet and we're still in `rc`, so I guess it is fine to do it now.

feat(react): export entire ServerDataContext instead Consumer only

---

packages/redux/action-creator-dispatcher/mixin.server.js

This fixes a bug that were introduced by #703 
The `prefetchedOnServer` member variable is used in [`packages/redux/action-creator-dispatcher/mixin.runtime-common.js`](https://github.com/xing/hops/blob/1b4b8eaa7c9f5c792ee3ce5ddc5638b4aa7d68a9/packages/redux/action-creator-dispatcher/mixin.runtime-common.js#L84)

fix(redux): always set prefetchedOnServer member variable

---

.travis.yml

During the last deployment the deployment script failed with a message
that it is not currently on any branch.
Therefore we will try to remove the branch restriction, because we use
tags only for releases anyway.
Unfortunately we need to merge this PR into master and do a release
before we can verify that this change works as intended, because we can
not test travis's deployment provider any other way.

chore: remove master branch restriction for tag deployment

---

packages/graphql/package.json
packages/jest-preset/package.json
packages/postcss/package.json
packages/pwa/package.json
packages/react/package.json
packages/redux/package.json
packages/spec/package.json
packages/styled-components/package.json
packages/template-graphql/package.json
packages/template-react/package.json
packages/template-redux/package.json
packages/typescript/package.json
yarn.lock

A couple of Hops packages have incorrect dependency versions in their
package.json files and some packages are missing required peer
dependencies.
This PR adds missing peer dependencies and increases the minimum
required versions of other dependencies to remove all peer dependency
warnings in Hops.

Fix dependency issues (minimum required versions, peer dependencies, etc)

---

.travis.yml
package.json
yarn.lock

This approach did not work, either the travis deployment provider or
the github script are broken.
Since this is not a high priority right now we will remove it again and
try to investigate when we have more time.

chore: remove broken github deployment script

---

packages/postcss/mixin.core.js
packages/postcss/package.json
yarn.lock

We need to find a way to deal with the breaking chante in import statements first.
Files loaded from node packages need to be prepended with `~`, but only for `composes` and not `@import`, because those are handled by `postcss-import`.
It's all pretty confusing and needs more thinking about.

Revert css loader

---

packages/create-hops-app/lib/package-manager.js

...when installing the Hops base package. I thought about make it configurable via CLI, but I guess there's no real need for that.

fix(create-hops-app): use user-defined version range

---

packages/jest-preset/jest-preset.js
packages/spec/integration/jest-preset/__tests__/preset.js
packages/spec/integration/jest-preset/__tests__/setup/global-css.js
packages/spec/integration/jest-preset/__tests__/setup/local-css.js
packages/spec/integration/jest-preset/__tests__/setup/style.css

It currently fails with `Cannot find module './yostyle.css?global'` when running tests that require js modules that import css files with `?global`.

fix(jest-preset): allow to use ?global for css imports

---

packages/development-proxy/mixin.core.js

This is also how the graphql mock server determines if it should be used

fix(development-proxy): Use NODE_ENV instead of mode to determine if proxy should run

---

packages/graphql/schema.js

The former error message was imho a little misleading, since there's only one way the `hops-graphql/schema.js` gets loaded: when the user names their schema file `schema.js`, too, and configures it by using a relative path. In this case the module resolving erroneously ends up at `hops-graphql/schema.js`. Then again telling the user they should not load this file directly is really confusing.
Did I miss a possible scenario?

chore(hops-graphql): improve error message

---

packages/jest-preset/jest-preset.js
packages/jest-preset/package.json
yarn.lock

This PR introduces the ability to `jest-preset-hops` to run tests written in `*.tsx?`. Currently Jest only runs tests written in Javascript (while it's already possible to import `*.tsx?`-modules into tests).
For the Typescript compiler to know what all those `describe()`, `it()`, etc. "gibberish" is all about, `@types/jest` is included as a dependency.
PS: with Jest v24 comes Typescript support out of the box. I guess all the changes of this PR will then be obsolete.

feat(jest-preset-hops): enable *.tsx test files

---

packages/graphql/README.md

docs(graphql): document graphqlMockServerPath config value

---

packages/template-graphql/package.json
packages/template-react/package.json
packages/template-redux/package.json

…for `@babel/preset-env`. This fixes insufficient transpiling/polyfilling of the build artifact, that users might actually not be aware of.

fix: use default browser matrix in templates

---

packages/spec/integration/typescript/__tests__/develop.js
packages/spec/integration/typescript/content.tsx
packages/spec/integration/typescript/headline.js
packages/spec/integration/typescript/index.tsx
packages/typescript/mixin.core.js
packages/typescript/tsconfig.json

This fixes two issues related to the current setup of hops-typescript:
- compiled Typescript code is not processed by `babel-polyfill`
- code-splitting with the `importComponent` function does not work in Typescript
refs #765

fix: babel ts-loader output

---

packages/spec/integration/hot-module-reload/__tests__/develop.js

This tests breaks pretty often on travis, presumably due to resource constraints.
https://travis-ci.org/xing/hops/builds/ 
E.g. I restarted https://github.com/xing/hops/pull/756 five times already and this test always broke (but in different jobs/node versions)

stabilize hmr test

---

packages/development-proxy/mixin.core.js

There is now a new way to configure the proxy: `proxy: { '/foo': 'target' }`
And it is also possible now to have an empty proxy target. This allows something like `proxy: '[PROXY_URL]'` to work even when the `PROXY_URL` env is not defined. But it produces a warning though.

Proxy improvements

---

packages/create-hops-app/index.js
packages/create-hops-app/lib/create-app.js
packages/create-hops-app/lib/init.js
packages/create-hops-app/lib/package-manager.js
packages/spec/integration/create-hops-app/__tests__/index.spec.js

I'm not sure if I'm missing something here, but I think by moving the bootstrap code into the `create-hops-app` package, we made `hops-version` obsolete.
The package is indeed installed, but as far as I can see never used. 
Installing the package also causes the peerDependency warnings described in #783  
You can still choose the hops version by running 
```
npx create-hops-app@myversion --template hops-template-react@myversion my-app
```

fix(create-hops-app): remove superfluous hops-version option

---

package.json
packages/spec/package.json

because the cli is being run from the workspace root rather than from
inside the spec/ folder.

chore: move jest dependency to root manifest

---

packages/spec/integration/jest-preset/tsconfig.json
packages/spec/integration/typescript/tsconfig.json

Until now we used to extend the tsconfig.json that is shipped with
hops-typescript from inside our integration tests.
This resulted in having to use brittle relative paths inside the
integration tests and will break for example when we use Hops inside
our citgm tool.

test(spec): include tsconfig directly to stabilize tests

---

.travis.yml
package.json
yarn.lock

This PR adds the [canarist](https://github.com/xing/canarist) tool to
run the test suites of downstream projects against the current Hops
build to assert that no breaking changes are being introduced.

chore: run canarist on travis

---

packages/graphql/package.json

`warning "workspace-aggregator-4739a636-8576-4a88-9914-8301a646242a > hops-graphql > react-apollo@2.4.1" has unmet peer dependency "react-dom@^15.0.0 || ^16.0.0".`

fix(graphql): add react-dom as peer dependency for react-apollo

---

packages/graphql/mixin.server.js
packages/redux/action-creator-dispatcher/mixin.server.js

This PR follows up on the discussion in https://github.com/untool/untool/pull/261.
We currently rely on the `fetchedData` property of the object passed to the `getTemplateData` hook to pass data between mixinstance methods. This appears to be rather indirect and brittle.
In this PR, I proposed removing that indirection and instead rely on instance props (or module scoped variables).
At some point down the road (`untool` v2) we might want to look into getting rid of the `data` argument of `fetchData` altogether since it does not appear all that useful any longer...

Simplify `fetchData`

---

packages/config/package.json
packages/create-hops-app/package.json
packages/development-proxy/package.json
packages/express/package.json
packages/graphql/package.json
packages/jest-preset/package.json
packages/lambda/package.json
packages/mixin/package.json
packages/postcss/package.json
packages/pwa/package.json
packages/react/package.json
packages/redux/package.json
packages/styled-components/package.json
packages/typescript/package.json

Add homepage field for each package so that `npm docs hops-package` will
lead to the the appropriate readme instead of the main entry.
I deliberately omitted `hops`, because I think the main readme makes sense their.
The templates are used as, well, templates so I did not think adding our repo as homepage makes sense there either.

docs: add proper home page urls

---

packages/config/package.json
packages/graphql/package.json
packages/hops/package.json
packages/lambda/package.json
packages/mixin/package.json
packages/pwa/package.json
packages/react/mixin.core.js
packages/react/package.json
yarn.lock

<details>
<summary>untool changelog</summary>
* **express:** rely on Express to add app to req ([f392af6](https://github.com/untool/untool/commit/f392af6))
* **react:** only allow arrow function with single import() statement ([2bbbdcc](https://github.com/untool/untool/commit/2bbbdcc))
* **webpack:** re-enable node source maps ([3f40319](https://github.com/untool/untool/commit/3f40319))
* **core:** introduce validation helpers ([c931a20](https://github.com/untool/untool/commit/c931a20))
* **express:** add arg validation to mixin methods ([2dca3f8](https://github.com/untool/untool/commit/2dca3f8))
* **react:** add arg validation to mixin methods ([c03e897](https://github.com/untool/untool/commit/c03e897))
* **react:** add arg/prop validation to public API …

Upgrade untool and recreate yarn.lock

---

.travis.yml

Right now the tests in the foosbyte repository which we are using to run
our canarist tests against, are failing randomly, therefore we will
disable canarist temporarily until the tests are fixed and stable again.

chore: disable canarist for now because foosbyte's tests are flaky

---

README.md
packages/spec/integration/react/index.js
packages/spec/integration/typescript/index.tsx

After [these changes](https://github.com/untool/untool/pull/271) were
released in untool, we can now optionally use arrow-functions as
arguments to `importComponent` which makes it a bit more user-friendly
by having additional editor support and support for type-checking.
This PR updates the usage examples and documentation to reflect that
change.

Update code examples and documentation for `importComponent`

---

.travis.yml

Speed up the time spent running travis tests by running everything in parallel:
- integration tests on Node 8.10
- integration tests on Node 10
- canarist tests on Node lts

chore: use build matrices to run tests and canarist in parallel

---

package.json

...by having it detect the current React version automatically. Because nobody wants to see this warning. 🤷‍♂️

chore: remove Eslint warning

---

packages/react/README.md

the docs still documented the state where we only exported the Consumer. 
Nowadays we export the entire context to allow it being used in `contextTypes` and hooks. :)

Fix ServerDataContext docs

---

packages/graphql/index.d.ts
packages/graphql/package.json
packages/hops/lib/runtime.d.ts
packages/hops/package.json
packages/pwa/index.d.ts
packages/pwa/package.json
packages/redux/index.d.ts
packages/redux/package.json
packages/styled-components/index.d.ts
packages/styled-components/package.json
yarn.lock

This commit adds TypeScript typings for runtime API in `hops` and
`hops-pwa` packages.
This pull request closes issue #360

feat: add typescript typings for runtime API and options

---

packages/graphql/lib/mock-server-middleware.js
packages/graphql/mixin.core.js

The Apollo server gets recreated for every request which is not needed. A weird side effect of that is that the request object never changes.
As we know the path it is not required to have other phases before this handler. The Apollo server gets created only once now (initially and via every HMR).

GraphQL middleware fixes

---

README.md
packages/hops/bin.js
packages/hops/mixins/analyzer/mixin.core.js
packages/hops/package.json
yarn.lock

Adds `--analyze-client-bundle` cli flag to `build` command.
Using it will add `webpack-bundle-analyzer` allowing teams to, well, analyze their bundles.
I picked the name `analyze-client-bundle` to allow to potentially add `analyze-server-bundle` at a later point. Imo there will never be more than two kinds of bundles to analyze so I considered two bools better and easier than using an enum.
Currently no options are passed to  the `webpack-bundle-analyzer`, which causes a server to be started and the analyzer page to be opened automatically.
I'm not sure what's best here. We could also configure it to write an .html file somewhere that users can open themselves. This would allow to add more stuff to the `analyze-client-bundle` flag, but would also come with less convenience.
What do you …

add cli flag to analyze client bundle

---

lerna.json
renovate.json

This PR will enable `--github-release` for lerna to automatically push
the release notes to the github releases page and
update the renovate configuration to use the prefix `fix` for
dependencies and peerDependencies and `chore` for devDependencies.
**Edit:** This requires the environment variable `GH_TOKEN` to be set: https://github.com/lerna/lerna/tree/master/commands/version#--github-release

Update tooling (changelog releases, renovate)

---

packages/redux/action-creator-dispatcher/mixin.server.js
yarn.lock

This pull request closes issue #831.
`hops-redux` [imports a `createLocation` utility](https://github.com/xing/hops/blob/5dbcce1308953513c95fbcd2218793d8c691ee7f/packages/redux/action-creator-dispatcher/mixin.server.js#L2) from [history package](https://github.com/ReactTraining/history) which from v4.9 is no more directly accessible as submodule.
Import `createLocation` from `history` as named export.
[history package](https://github.com/ReactTraining/history) doesn't provide **official documentation** about **accessing `createLocation`** utility.
`createLocation` is **currently available** as named export in both `history` **v4.7.2** and **v4.9**, but as long it's **not officially documented**, it might get potentially removed.
Should address #828 & #830.

fix(redux): import "createLocation" from "history"

---

packages/config/package.json
packages/graphql/package.json
packages/hops/package.json
packages/lambda/package.json
packages/mixin/package.json
packages/pwa/package.json
packages/react/package.json
yarn.lock

This pull request should address #830
Hops relies on Untool v1.3.1.
Update Untool dependency to v1.4.0.

chore: upgrade untool to v1.4.0

---

packages/hops/package.json
packages/react/package.json
packages/redux/package.json
packages/template-graphql/package.json
packages/template-react/package.json
packages/template-redux/package.json
yarn.lock

This pull request replaces #830
Open `react-router-dom` dependency to **v^4.3.1** ot **v^5**.

fix(dependencies): update dependency react-router-dom to v^4.3.1 || v^5

---

packages/config/package.json
packages/graphql/package.json
packages/hops/package.json
packages/lambda/package.json
packages/mixin/package.json
packages/pwa/package.json
packages/react/package.json
yarn.lock

* **webpack:** polyfill EventSource to make HMR work on Win/Edge ([50071dc](https://github.com/untool/untool/commit/50071dc))
* **webpack:** use async-node target to circumvent Node 11.11.0 bug ([3b6cada](https://github.com/untool/untool/commit/3b6cada))
* **webpack:** use events instead of signals to make hmr work on windows ([dfae72a](https://github.com/untool/untool/commit/dfae72a))
* **webpack:** improve cross plattform compatibility ([23b2c36](https://github.com/untool/untool/commit/23b2c36))
* **webpack:** prevent core-js transpilation on windows ([f11e4f3](https://github.com/untool/untool/commit/f11e4f3))
* **core:** add "absolutePath" keyword to ajv config validation ([7dca480](https://github.com/untool/untool/commit/7dca480))

fix: upgrade untool to v1.5.0

---

packages/redux/README.md
packages/redux/action-creator-dispatcher/mixin.runtime-common.js
packages/redux/action-creator-dispatcher/mixin.server.js
packages/spec/integration/redux/__tests__/develop.js
packages/spec/integration/redux/index.js

This pull request closes issue #821 
As already discussed and proposed in #821 this could be a very useful feature.
Currently actions in the `actionCreators` array only receive one parameter (`params`). 
Actions will receive an additional parameter: an object containing the `location` and `match` objects from `react-router`. This enables the action creator to access to the search query, the current pathname, matched path etc.
`createLocation` utility gets now called with [`request.originalUrl`](https://expressjs.com/en/api.html#req.originalUrl) instead of the original [`request.path`](https://expressjs.com/en/api.html#req.path).
I also added a new paragraph to the documentation to explain the (currently undocumented) parameters that actions receive in `actionCreators`. The code-example …

Add second parameter "location" to actions in "actionCreators"

---

packages/jest-preset/package.json

Since the jest-preset depends on the `hops` package which expects
certain peerDependencies (such as react, react-dom, etc), we need to
re-declare these packages as peerDependencies on the jest-preset itself
to get rid of peer dependency warnings when the jest-preset is installed

fix(jest-preset): correctly specify peer dependencies

---

packages/create-hops-app/package.json

This PR removes the workaround for "yarn create hops-app@next" hack
https://github.com/xing/hops/pull/708
And it also removes an unused dependency to "hops" which led to
peerDependency warnings when installing / using create-hops-app globally
Technically this could be considered a breaking change, because it
removes the `create-hops-app@next` binary, but since it was a hack and
was probably only used while we were working on the Hops 11 RC, I think
we could argue to remove it.

Clean up create-hops-app package

---

packages/development-proxy/preset.js

We allow the proxy target to be empty in order to support a case where the proxy can get optionally enabled by providing an environment variable.
Example:
```js
proxy: {
'/my/api': '[PROXY_URL]',
},
```
But that produces the following warning:
```
crate:warning Invalid configuration value(s) detected:
- config.proxy should be string
- config.proxy['/my/api'] should match format "uri"
- config.proxy['/my/api'] should be object
- config.proxy['/my/api'] should match exactly one schema in oneOf
- config.proxy should match exactly one schema in oneOf
```
An empty string is also valid now.

fix(development-proxy): allow empty proxy targets in config

---

packages/lambda/preset.js

Not sure what difference this makes - in my tests it worked the same
but we should try to stay consistent and this is the proper way to
annotate an object in JSON schema.

refactor(lambda): use object type for schema validation

---

packages/redux/mixin.browser.js
packages/redux/mixin.runtime-common.js
packages/redux/mixin.server.js

By calling `render(app, { redux: { middlewares } })` it is possible to pass in your own redux middlewares however by doing so the `getReduxMiddlewares` mixin hook gets ignored.
This might not be a bug but at least makes it impossible to have mixins with redux middlewares combined with own middlewares.
The middlewares coming from render are now added into the result of `getReduxMiddlewares` and `ReduxThunkMiddleware` comes last as this means that it does not break an existing thunk middlware. This works because you can only have one `ReduxThunkMiddleware` and the first in the list wins.
~I also introduce a `configureReduxThunkExtraArgument` here in order to make it easier to add more entries to the extra argument object.~

Redux middlwares

---

packages/graphql/preset.js

...to be an absolute path, because it is consumed via `require.resolve`
and can thus be a module identifier, too.

fix(graphql): do not require mock schema file

---

packages/jest-preset/package.json
packages/jest-preset/transforms/babel.js
packages/react/package.json
yarn.lock

This fixes an issue where people had an older version of
`@babel/preset-env` in their `yarn.lock` file which didnt recognize the
`corejs` option and would therefore throw an error when running the jest
test suite.

fix: upgrade babel dependencies and remove obsolete object-rest-spread

---

packages/postcss/mixin.core.js
packages/postcss/package.json
yarn.lock

...since they should not be relevant in the context of scoped CSS
modules. For more informations check out [sokra's comment](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-415345126)
and the surrounding content of the issue.

fix(postcss): filter conflicting order warnings

---

package.json

This is needed for renovate, which commits with
`fix(dependencies): xxx` or
`chore(dependencies): xxx`.

chore: add scope "dependencies" to allowed commitlint scopes

---

package.json

With this we can remove the workaround from untool:
https://github.com/untool/untool/blob/master/package.json#L95-L99

chore: remove pinned ts-loader workaround from canarist

---

packages/postcss/mixin.core.js

fix: rename "browsers" option for postcss to silence deprecation warning

---

renovate.json

Pimp our renovate config with more specific rules:
- add "untool" as package to the untool monorepo group filter
- **peerDependencies** should be "widened (ie: `"react": "15 || 16"` instead of upgrading to `16`)
- **devDependencies** should be bumped (ie: an update from `prettier@^1.0.0` to `prettier@1.1.0` which would normally fall under our version range, should be updated to the new range: `"prettier": "^1.1.0"`)
- **devDependencies in the root `package.json`** should be auto merged if they are a minor or patch upgrade

Improve renovate config

---

packages/graphql/mixin.server.js
packages/spec/integration/graphql/__tests__/develop.js
packages/spec/integration/graphql/index.js
packages/spec/integration/graphql/mixin.core.js

`wrapNetworkError` should return the error instead of throwing it.
Thanks @herschel666

Return error

---

packages/styled-components/package.json
yarn.lock

The `babel-plugin-styled-components` introduced a bug in v1.10.3 which
causes our builds to get stuck endlessly.
This commit temporarily restricts the version range of the babel plugin
to the safe versions until the bug is fixed upstream.
See this PR and its linked issue for more details:
https://github.com/styled-components/babel-plugin-styled-components/pull/233

fix(styled-components): temporarily restrict babel plugin version

---

packages/development-proxy/mixin.core.js

The http-proxy-middleware option is called [`router`](https://github.com/chimurai/http-proxy-middleware#http-proxy-middleware-options) not `routes`.
But as that feature isn't documented nor in use I propose to just delete it for now.

chore(development-proxy): remove non-existing routes option

---

packages/spec/integration/typescript/tsconfig.json
packages/typescript/README.md
packages/typescript/package.json
yarn.lock

BREAKING CHANGE:
In order to improve flexibility we changed TypeScript to be a peer dependency now.
Please install at least v3.6.0 of the `typescript` package.

feat(typescript): make typescript a peer dependency

---

packages/hops/lib/runtime.d.ts

BREAKING CHANGE: `withConfig` and `withServerData` have a simpler type definition now. They only take one generic argument instead of three.

feat(hops): simplify typings

---

DEPRECATIONS.md
packages/config/browser.js
packages/config/package.json
yarn.lock

The commit message's body:
Instead of importing the `config`-object from a package, you should
rather use `ConfigContext` or the `withConfig()`-HOC from `hops`.
**Example using `ConfigContext`**
```jsx
import React from 'react';
import { ConfigContext } from 'hops';
const Comp = () => {
const config = React.useContext(ConfigContext);
return <em>{config.basePath}</em>;
};
```
**Example using `withConfig` HOC**
```jsx
import React from 'react';
import { withConfig } from 'hops';
const Comp = withConfig(({ config }) => (
<em>{config.basePath}</em>
));
```

chore(config): deprecate hops-config package

---

README.md
packages/hops/lib/runtime.d.ts
packages/hops/lib/runtime.js
packages/react/README.md
packages/react/config/use-config.js
packages/react/index.js
packages/react/server-data/use-server-data.js
packages/spec/integration/react/__tests__/develop.js
packages/spec/integration/react/index.js
packages/spec/integration/react/package.json

btw: why don't we lint files in `packages/spec`??
~~And I would propose to deprecate the exports of `ConfigContext` & `ServerDataContext` and eventually make them private in Hops 13. They're imho our private turf & users should not directly interact with them, but rather with the API wrappers we provide — HoCs & hooks.~~

feat(react): provide hooks for config & server-data contexts

---

package.json
packages/typescript/package.json
yarn.lock

FYI: I decided to make this an implicit, follow-up breaking change in order to not pollute the Hops 12 changelog with redundant messages. What do you think?

feat(typescript): update typescript to v3.7

---

packages/apollo-mock-server/context-extender.js
packages/apollo-mock-server/lib/mock-server-middleware.js
packages/apollo-mock-server/mixin.core.js
packages/apollo-mock-server/preset.js

This allows users of the mock server to extend the graphql context by a function.

feat: create context extender api

---

packages/apollo-mock-server/mixin.core.js

This check is also happening in `hops-react-apollo`, where the command for executing the introspection query is located, too.

chore(apollo-mock-server): remove redundant warning

---

packages/spec/integration/typescript/package.json
packages/typescript/README.md
packages/typescript/mixin.core.js
packages/typescript/package.json
yarn.lock

- strongly recommend to extend `hops-typescript`'s `tsconfig.json`
- check, that the `compilerOptions` `target`- and `moduleResolution`-properties aren't overwritten by the user
- speed up incremental builds by setting `transpileOnly` and `compilerOptions.isolatedModules` to `true` for the dev-server
I'm overall not happy with how the checks are done in the `diagnosis()`-hook & don't lead to an error. Does anyone have a good idea to improve that?
Also the `transpileOnly`-feature doesn't lead to `compilerOptions.isolatedModules` being set to `true` anymore since [this PR](https://github.com/TypeStrong/ts-loader/pull/569), that apparently fixed [this issue](https://github.com/TypeStrong/ts-loader/issues/568). Maybe we don't want to enable it either, but I'm not able to decide this now. 😑

Typescript changes

---

packages/jest-preset/package.json
packages/jest-preset/transforms/babel.js

Not sure if we should wait for https://github.com/babel/babel/pull/10146
to be released until we release this?

alias core-js in jest-preset to correct version

---

packages/apollo-mock-server/README.md
packages/apollo-mock-server/mixin.core.js
packages/apollo-mock-server/package.json
packages/react-apollo/mixin.core.js

This fixes a bug introduced in #997 
The issue is that we also need the `graphql-tag` configuration for the mock server because otherwise we can't import a `schema.graphql` file.

Fix graphql tag loader

---

packages/spec/helpers/env.js
packages/spec/helpers/test-helpers.js

* The workdir of the tests can only be deleted if the server process is
terminated. Therefore we shift this cleanup to a later step.
* The spawned test process need to be run explicitly with node, since
shebangs are not valid in the windows world.

test: correct test setup for windows

---

packages/spec/integration/graphql-mock-server/package.json

Apparently we have race conditions when we rely on the browser fetching
the graphql data in the untool canarist tests.
And since we test server and client-side fetching/rendering of graphql
data in the integration tests for graphql, we can switch to server-side
rendering in the graphql-mock-server-tests.
See: https://github.com/untool/untool/pull/523
and: https://travis-ci.org/untool/untool/jobs/633264357

test: fetch graphql data during ssr

---

packages/spec/integration/graphql-mock-server/index.js
packages/spec/integration/graphql/index.js
packages/spec/integration/hops/index.js
packages/spec/integration/hot-module-reload/index.js
packages/spec/integration/lambda/index.js
packages/spec/integration/postcss/index.js
packages/spec/integration/pwa/index.js
packages/spec/integration/react/index.js
packages/spec/integration/redux/index.js
packages/spec/integration/styled-components/index.js
packages/spec/integration/typescript/index.tsx
packages/spec/package.json

This adds a favicon to all cases, since if run in debug mode
(with open browser window) a request for the favicon
is made. Since there is no favicon in the test, the request is
replied with a 404 warning.
In the spec test set, there is a check that there are no unknown
console output in the test cases.
Unfortunately the 404 favicon request does not report a
path for the favicon but just a generic 404 error. Therefore
we are not able to whitelist this message without risking
false positives in the test.
Adding an inline favicon supresses these requests entierly
getting around the above problem.

test: add favicon to all test cases

---

packages/create-hops-app/package.json

Backport for v12.x of https://github.com/xing/hops/commit/1390ab66c18dbfb4e51f91ce31390d37a877d17e

fix(create-hops-app): remove @next bin workaround

---

package.json
packages/spec/integration/create-hops-app/__tests__/index.spec.js

I created a dedicated Hops-11-branch in `foosbyte/kicker-trainer`. We could then delete the `next`-branch.

chore: use hops-v11.x-branch of foosbyte/kicker-trainer

---

packages/lambda/lambda.js
packages/spec/integration/lambda/__tests__/build.js
packages/spec/integration/lambda/index.js
packages/spec/integration/lambda/package.json

This issue became obvious to me, when the lambda test failed with `Node version 13.8 is not supported.`, although in the Hops config the Node version was set to `10.13`.

fix(lambda): pass Hops config into server app

---

packages/jest-preset/helpers/babel-plugin-rename-corejs.js
packages/jest-preset/jest-preset.js
packages/jest-preset/transforms/babel.js
packages/spec/integration/typescript-unit-testing/__tests__/index.js
packages/spec/integration/typescript-unit-testing/content.tsx
packages/spec/integration/typescript-unit-testing/headline.js
packages/spec/integration/typescript-unit-testing/index.tsx
packages/spec/integration/typescript-unit-testing/package.json
packages/spec/integration/typescript-unit-testing/tsconfig.json
packages/spec/package.json
packages/template-redux/src/counter/index.js
yarn.lock

Since hops depends on a few babel-plugins (e.g. for importComponent) we
need babel to process all files, even in the case of unit tests.
This PR implements the required setup of ts-jest to include the babel
config for hops. This declares that ts-jest should babel all files,
after transpiling with typescript.

fix: all test files need to run through babel

---

.gitignore
package.json
packages/jest-preset/helpers/babel-plugin-import-component.js
packages/spec/integration/hops/__tests__/__snapshots__/import-component-loading.js.snap
packages/spec/integration/hops/__tests__/__snapshots__/import-component-mocked.js.snap
packages/spec/integration/hops/index.js

When executing jest with `jest --coverage` it adds coverage instrumentation
code to the source code which breaks our babel plugin for the
`importComponent` function. With this change we can correctly handle
instrumented code.
Closes: #1080

fix(jest-preset): correctly handle coverage instrumented importComponent

---

.travis.yml

Bors will take care of running the full test suite including canarist
tests on all other Node.js versions.

chore: only execute linters and tests on latest Node for PRs

---

packages/apollo-mock-server/package.json
packages/config/package.json
packages/hops/package.json
packages/lambda/package.json
packages/mixin/package.json
packages/pwa/package.json
packages/react-apollo/package.json
packages/react/package.json
yarn.lock

Changes:
* update dependency serialize-javascript to v3 ([1e0aadb](https://github.com/untool/untool/commit/1e0aadb51e90c95435ed3370af2e48d68fa3f121))
* **core:** allow to ignore certain presets through "ignoredPresets" ([1dc9422](https://github.com/untool/untool/commit/1dc942266cd47d2d496afafcec405b3130624719)), closes [#580](https://github.com/untool/untool/issues/580)
* **react:** set data-mounted attribute after hydration ([566a3a5](https://github.com/untool/untool/commit/566a3a55d631f89113acc7c5390123688310cda6))
<details>
We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members of this repository with …

fix: upgrade untool to v2.1.3

---

package.json

chore: use master branch of foosball trainer for canarist tests

---

packages/react/config/mixin.runtime.js

...in config proxy, to prevent warnings concerning a missing
"@@toStringTag"-property.

fix(react): ignore prop-types symbol check

---

.travis.yml

The travis yarn cache is currently broken for us. It might be related to the fact that Travis is using a different yarn version for the cache and the installation but we are not sure yet.
Let's disable this feature for now, we can come back to it later.

chore: disable yarn cache on travis

---

packages/redux/action-creator-dispatcher/mixin.runtime-common.js
packages/spec/integration/redux/__tests__/develop.js
packages/spec/integration/redux/index.js

fix(redux): prevent route actions from being dispatched on hashchange

---

packages/redux/action-creator-dispatcher/mixin.runtime-common.js
packages/spec/integration/redux-without-ssr/__tests__/develop.js
packages/spec/integration/redux-without-ssr/index.js
packages/spec/integration/redux-without-ssr/package.json

fix(redux): ensure to really only ignore hash-changes in dispatcher

---

packages/redux/action-creator-dispatcher/mixin.runtime-common.js
packages/spec/integration/redux-without-ssr/__tests__/develop.js
packages/spec/integration/redux-without-ssr/index.js
packages/spec/integration/redux-without-ssr/package.json

Release v12.1.4

---

DEPRECATIONS.md
packages/mixin/index.js
packages/mixin/package.json

chore: deprecate "hops-mixin" in favor of "hops-bootstrap"

---

package.json
packages/jest-preset/helpers/__tests__/babel-plugin-import-component.js
packages/jest-preset/package.json
packages/jest-preset/transforms/babel.js
packages/webpack/lib/configs/node.js
packages/webpack/package.json

fix: remove unnecessary babel plugin dynamic import node

---

packages/webpack/mixins/build/mixin.core.js
packages/webpack/mixins/config/mixin.core.js
packages/webpack/package.json
yarn.lock

This commit adds a new CLI option `--profile` to the `build` command.
Use it to display build performance stats after a build.
Example: `hops build --profile` or `hops build --production --profile`
<details>
| --- | --- |
| bors try | Run the test suite without pushing …

feat(webpack): add profiling mixin to show performance stats

---

packages/typescript/mixin.core.js

perf: use transpileOnly flag of ts-loader for node dev build

---

packages/express/mixins/mixin.core.js

fix(express): use nocache module to skip deprecation warning

---

packages/redux/action-creator-dispatcher/mixin.runtime-common.js

fix(redux): remove usage of unsupported es class properties

---

packages/webpack/lib/plugins/stats.js

We only serialized all stats to disk, so that users may be able to
inspect them with the webpack bundle analyzer.
But since we've introduced `hops build --analyze-client-bundle` the
full stats file is no longer necessary.
<details>
| --- | --- |
| bors try | Run the test …

perf: reduce memory footprint by not serializing all stats

---

packages/react/helmet/mixin.runtime.js
packages/react/render/mixin.server.js
packages/spec/integration/react/__tests__/develop.js

This pull request closes issue # (_no issue yet_)
As specified in the [documentation of `react-helmet-async`](https://github.com/staylor/react-helmet-async#usage) it will create a property `helmet` in the object passed as context. Back when the [react package from untool](https://github.com/untool/untool/blob/ef7abccc693ee5fb24c1c17bc7a33098aafed0b1/packages/react/mixins/mixin.server.js#L47) was used, this context was saved in a context variable and later its `helmet` key was used. Now the context is saved in a variable `helmet`, but the nested `helmet` key of this context is never taken out. So instead of adding keys like `title`, `base`, `meta`, etc. to the fragments so they can be rendered by the template, only a key called `helmet` is added which the template silently ignores. This …

fix(react): render react-helmet-async values on the server again

---

packages/react/helmet/mixin.runtime.js
packages/react/render/mixin.server.js
packages/spec/integration/react/__tests__/develop.js

As specified in the documentation of react-helmet-async[1] it will create
a property helmet in the passed context. Back when the react package from
untool[2] was used, this was saved in a context variable and later taken out.
Now the context is saved in a helmet variable, but the nested helmet key is
never taken out. So instead of adding keys like title, base, meta, etc. to
the fragments, only a key called helmet was added, so everything set by helmet
got lost on the server. Luckily the client immediately fixes that, so the problem
went unnoticed for some time.
This adds back the context concept and then properly takes out the helmet
key form it, so that the individual entries are copied to the fragments again.
Also it adds an integration test to see that it actually works and to avoid …

fix(react): render react-helmet-async values on the server

---

packages/typescript/mixin.core.js

fix: use the correct type to determine ts target

---

packages/webpack/lib/plugins/log.js

example output:
```
hops-demo:info bundling 'node' finished after 30.7s (12.4 MB)
hops-demo:info bundling 'build' finished after 51.2s (7.34 MB)
```

feat(webpack): print total bundle size

---

.prettierignore
packages/webpack/mixins/build/mixin.core.js
packages/webpack/package.json
yarn.lock

Reverts xing/hops#1224
It's not been the right approach unfortunately. The issue isn't per sé that there are multiple major versions around. The issue's rather that a dependency might import from `core-js` & thereby expects a different major version, which leads to errors, because the structure of the deep imports has changed.
So the way to go is rather to listen for those errors & tell the user, that this specific dependency is doing it wrong.

Revert "feat(webpack): improve feedback on conflicting core-js versions"

---

packages/webpack/lib/plugins/log.js
packages/webpack/lib/utils/errors.js

I added the temporary commit [`e13a9a6`](https://github.com/xing/hops/pull/1238/commits/e13a9a657592b07f92efa15bda1590f7a17bf888), so it's possible to check out the message. Just run…
```
$ (cd packages/spec/integration/react/ && ../../../../node_modules/.bin/hops start)
$ (cd packages/spec/integration/react/ && ../../../../node_modules/.bin/hops build)
```
…in your terminal and witness its beauty. :p
<details>
| --- | --- …

feat(webpack): improve error output for core-js issues

---

DOCUMENTATION.md
packages/webpack/README.md
packages/webpack/lib/configs/node.js
packages/webpack/lib/shims/node.js
packages/webpack/mixins/fast-dev/mixin.core.js
packages/webpack/mixins/optimizations/mixin.core.js
packages/webpack/package.json
packages/webpack/preset.js

The new experimental `--fast-build` feature only transpiles some node_modules instead of all.
That also requires to change core-js `useBuiltIns` to `entry` as we don't know which polyfills we need in the end.
**`hops build -p`**
```
fixture-hops:info bundling 'node' finished after 8.4s (2.92 MB)
- server.js (2.89 MB)
- stats.json (33 kB)
fixture-hops:info bundling 'build' finished after 8.4s (1.69 MB)
- fixture-hops-0-1b0f62f1564b.js (255 B)
- fixture-hops-2-ef56cba710d4.js (338 kB)
- fixture-hops-ad490021bce4.js (39.5 kB)
```
**`hops build -p --fast-build`**
```
fixture-hops:info bundling 'node' finished after 3.2s (2.56 MB)
- server.js (2.53 MB)
- stats.json (33 kB)
fixture-hops:info bundling 'build' finished after 3.8s (1.68 MB)
- fixture-hops-0-1b0f62f1564b.js (255 B)
- …
```

feat(webpack): introduce experimental fast-build mode

---

.travis.yml

Also: Not sure what happened to the formatting, but prettier thinks that
this is correct now.
**Attention:** We can only merge this PR after we have released a new Hops version with updated `engines` field that allows Node.js v14.
<details>
| --- | --- |
| bors try | Run …

chore: use Node.js latest current release (v14) on travis

---

.prettierignore
packages/webpack/mixins/build/mixin.core.js

the `./build`-folders came in with the merge of untool into hops. that's why they're still pretty nicely formatted. but things will slowly go south, if we don't have them formatted automatically.
<details>
| --- | --- |
| bors try | Run the test suite without pushing to …

chore: add ./build-folders from prettifying

---

packages/webpack/mixins/build/mixin.core.js

fix(webpack): re-enable the --fast-build CLI flag

---

packages/bootstrap/lib/loader.js
packages/bootstrap/lib/resolver.js

This pull request closes issue https://github.com/xing/hops/issues/1257
**Detailed explanation and analysis can be found in [the related issue](https://github.com/xing/hops/issues/1257)**
As described in [the issue](https://github.com/xing/hops/issues/1257):
Resolving peerDependencies of a **symlinked** hops mixin-and-preset package fails, even when using the [`--preserve-symlinks` node arg](https://nodejs.org/api/all.html#cli_preserve_symlinks) which as describe in the official node documentation as a way to interpret node resolution algorithm to treat symlinks as preserved (as if they are normal dirs). Further detailed article can be found [here](https://chevtek.io/you-can-finally-npm-link-packages-that-contain-peer-dependencies/).
In [the resolver of bootstrap …

fix: module resolution in symlinked package of a preset

---

packages/apollo-mock-server/mixin.core.js
packages/spec/helpers/env.js
packages/spec/integration/lambda/__tests__/build.js
packages/spec/integration/postcss/__tests__/build.js
packages/spec/integration/react/index.js
packages/webpack/README.md
packages/webpack/index.js
packages/webpack/lib/middlewares/render.js
packages/webpack/lib/middlewares/stats.js
packages/webpack/lib/plugins/stats.js
packages/webpack/lib/utils/compiler-fork.js
packages/webpack/lib/utils/compiler.js
packages/webpack/mixins/build/mixin.core.js
packages/webpack/mixins/develop/mixin.core.js
packages/webpack/mixins/render/mixin.core.js
packages/webpack/mixins/stats/mixin.core.js
packages/webpack/package.json
yarn.lock

Successor of #1256
When the new `--parallel-build` CLI argument is set to true (which is the default)
we will fork the process for each Webpack compilation into a new child process.
This helps to reduce the peak memory consumption because we don't need to rely on the GC to clean everything up as the
child process stops right after the compilation has finished.
The build might also be faster as we can use more CPU cores but that improvement isn't as significant as I was hoping for though.

feat(webpack): introduce parallel build

---

package.json
packages/jest-preset/package.json
packages/spec/package.json
packages/template-graphql/package.json
packages/template-react/package.json
packages/template-redux/package.json
yarn.lock

BREAKING CHANGE: Jest peerDependency has been moved from 24->26
<details>
| --- | --- |
| bors …

fix: upgrade jest to v26

---

packages/webpack/lib/plugins/stats.js

Seems like this has gotten lost during the parallel build feature: https://github.com/xing/hops/commit/30ad91c2eccfbd103ca40290cdc0f8a655651da6#diff-5fe2ecdd50bbcabc5564903e94169121L72
<details>
| --- | --- |
| …

fix(webpack): reset stats file / promise on watch run events

---

DEPRECATIONS.md
packages/bootstrap/README.md
packages/bootstrap/index.js

Otherwise, we would need to add mixinable to all internal Hops packages which would
be unfortunate and also makes it possible to have multiple versions of mixinable in
the app if the versions diverge.
The deprecation got introduced in #1162 and is only available in v13 AFAICT.

fix(bootstrap): re-export strategies in hops-bootstrap

---

packages/spec/integration/graphql/__tests__/develop.js
packages/spec/integration/graphql/index.js
packages/spec/integration/graphql/package.json

This test verifies that a GraphQL response has been rendered onto the
page.
We have another test (./packages/spec/integration/graphql-mock-server/__tests__/develop.js)
which also verifies that a GraphQL response has been rendered.
The mock-server test uses our own GraphQL mock server instead of a
third party.
The problem here is that the GraphQL test uses a third party server
which is not available anymore and therefore our tests are failing.
By switching to our own mock server we are not relying on external
services anymore.
<details>
We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members of this repository …

test: remove redundant failing graphql test

---

packages/webpack/lib/middlewares/render.js

This was implemented previously already but got lost during the
implementation of another feature which was intended to reduce memory
consumption.
We are using webpack hot module reload for the server bundle, to be able
to update a running server with incremental changes.
In order to use the HMR on the server side, we need to send a signal to
the process which tells webpack to reloaad the module.
This is the part that got lost and instead we re-required the server
bundle every time a watch event happened on the webpack compiler.
In the current implementation we require the server bundle just once and
let webpack HMR handle all other updates.
<details>
We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull …

fix(webpack): use webpack HMR for node build to fix memory leak

---

packages/jest-preset/jest-preset.js
packages/jest-preset/package.json
yarn.lock

feat(jest-preset): print an error when Jest version is unsupported

---

bors.toml

chore: block bors on missing pr status and block labels

---

yarn.lock

...in order to get rid of the issue:
```txt
fixture-hops:warning ./node_modules/event-source-polyfill/src/eventsource.js 94:6-62
Critical dependency: the request of a dependency is an expression
```
<details>
| --- | --- |
| bors try | Run the test suite without pushing …

chore: update event-source-polyfill locally

---

packages/webpack/lib/utils/compiler-fork.js
packages/webpack/lib/utils/compiler.js
packages/webpack/lib/utils/errors.js
packages/webpack/package.json

For some reason, serialize-error is unable to successfully detect and resolve a circular error object. The result is an out-of-memory error when the compilation fails. I haven't tested if this is the case for all errors or only some specific ones though.
Another flaw of the previous implementation is that we lose the information whether the error is a compile or build error as the error deserialization always created a plain `Error` instance.
And as an error object only consists of the [three fields `name`,  `message` and  `stack`](https://github.com/microsoft/TypeScript/blob/7c6462aa10329884618c51ff9af76c66b503f47c/lib/lib.es5.d.ts#L972-L976
) the serialization of any other fields seems unnecessary to me.

fix(webpack): replace serialize-error with a custom implementation

---

packages/lambda/mixin.core.js

- fix condition concerning `basePath` and `assetPath`
- ensure warnings are printed
<details>
| --- | --- |
| bors delegate+ | Allow the pull request author to merge their changes. …

Fix lambda diagnosis hook

---

packages/jest-preset/jest-preset.js

The current implementation compares the string `"2"` with the number `26`. This commit should™ fix it.
<details>
| --- | --- |
| bors delegate+ | Allow the pull request author to …

fix(jest-preset): fix warning in case of outdated Jest version

---

packages/webpack/lib/utils/errors.js

A small typo slipped through 😬
The other side is correct though:
https://github.com/xing/hops/blob/143089a668a541de2542a4c50924ed9df03fc716/packages/webpack/lib/utils/errors.js#L62

chore: correct error name for deserialization

---

DOCUMENTATION.md
README.md
packages/bootstrap/README.md
packages/development-proxy/README.md
packages/react/README.md
packages/webpack/README.md
packages/yargs/README.md

docs: update documentation for Hops 13 and remove last untool references

---

packages/create-hops-app/package.json

fix(create-hops-app): remove "@next" suffix of binary

---

bors.toml

Our current implementation of the canarist bot doesn't allow for
complex configuration with three or more repositories which we would
need in this case.
Therefore we remove this check until we have updated our bot.
<details>
| --- | --- |
| bors try | Run the test suite …

chore: remove canarist check for workshop repository

---

packages/webpack/lib/utils/errors.js

This is required for deserialization:
https://github.com/xing/hops/blob/665eb0f9bdf6b979f48c74f2babb6d7268b2ec58/packages/webpack/lib/utils/errors.js#L22-L24

fix(webpack): accept object argument in BuildError

---

packages/bootstrap/lib/resolver.js

They're not relevant for Hops presets and lead to packages being
resolved, that aren't qualified Hops presets, like e.g. `tslib`.
<details>
| --- | --- |
| bors delegate+ | Allow …

fix(bootstrap): ignore exports fields when resolving presets

---

packages/spec/integration/typescript-styled-components/__tests__/develop.js
packages/spec/integration/typescript-styled-components/index.tsx
packages/spec/integration/typescript-styled-components/package.json
packages/spec/integration/typescript-styled-components/tsconfig.json
packages/typescript/mixin.core.js
packages/typescript/tsconfig.json

fix(typescript): preserve JSX when styled-components are present (v13.x)

---

packages/spec/integration/typescript-styled-components/__tests__/develop.js
packages/spec/integration/typescript-styled-components/index.tsx
packages/spec/integration/typescript-styled-components/package.json
packages/spec/integration/typescript-styled-components/tsconfig.json
packages/typescript/mixin.core.js
packages/typescript/tsconfig.json

fix(typescript): preserve JSX when styled-components are present (v12.x)

---

DEPRECATIONS.md
packages/info/README.md
packages/info/doctor/index.js
packages/info/doctor/mixin.core.js
packages/info/doctor/validators/generic.js
packages/info/package.json
packages/spec/helpers/env.js
packages/spec/helpers/test-helpers.js
packages/spec/integration/doctor/__tests__/build.js
packages/spec/integration/doctor/__tests__/develop.js
packages/spec/integration/doctor/index.js
packages/spec/integration/doctor/mixin-a/mixin.core.js
packages/spec/integration/doctor/mixin-b/mixin.core.js
packages/spec/integration/doctor/package.json

**ToC**
- the `doctor` got two new methods: `pushWarning(message: string)` and `pushError(tag: string, message: string)`; errors are completely listed, the last one ends the process with exit code `1`
- the `diagnose`-hook got a second argument: `mode: string`, which is either `build`, `develop`, `serve`, `build-serve` or `indeterminate`.
- errors can be converted into non-fatal warnings, by passing their tag via `HOPS_IGNORE_ERRORS` into the Hops command
- the test-helper's `HopsCLI`-object's `start`- & `build`-methods now take environment variables
- the test-helper's `HopsCLI`-object's `start`- & `build`-methods make their `stderr`-output available to the test environment
The changes to the `HopsCLI`-object are needed in order to be able to test the `doctor`. Let me know, if you'd …

Improve diagnose hook

---

packages/info/logger/mixin.core.js
packages/info/logger/mixin.server.js

feat(info): make logger available in server runtime

---

packages/info/logger/mixin.core.js
packages/info/logger/mixin.server.js

picks #1404 
<details>
| --- | --- | …

feat(info): make logger available in server runtime (v13)

---

packages/jest-preset/README.md
packages/jest-preset/jest-preset.js
packages/jest-preset/package.json
yarn.lock

Contains Breaking Change: `babel-jest & ts-jest need to be installed additionally now in order
to set up Jest for Hops.`
<details>
| --- | --- |
| bors delegate+ | Allow the pull …

feat: make jest-preset-hops more flexible

---

packages/webpack/lib/plugins/stats.js

Previously the closure that resets the enhancedPromise shared the same
context (variable bindings) as the closure to the additionalAssets hook
and since the closure for the additionalAssets hook needs access to the
compilation object, it was retained through the closure to the watchRun
hook, even though it wasn't referenced there.
By moving the watchRun hook up one level its closure no longer shares
the context object with the additionalAssets closure.
<details>
We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members of this repository with push access) and delegates (in case of `bors delegate+` or `bors …

fix(webpack): fix memory leak in StatsWriterPlugin

---

packages/webpack/mixins/optimizations/mixin.core.js

We should only compile for the latest chrome version in fast dev mode.
Leaving the old browsers list in there causes code to be down-transpiled
into an older version and transpiles async functions to regeneratorRuntime
<details>
| --- | --- |
| bors try | Run the test …

fix(webpack): compile browser bundle for latest chrome only

---

bors.toml

For some reason bors always seems to forget the pr_status and wait on a
status even when all statuses are green.
It might be an issue with bors or it might be heroku which might suspend
the instance if there are no requests for a given timeframe, but anyway
I'll remove the checks again, because it brings us more frustration than
joy.
<details>
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. …

chore: remove pr_status from bors config

---

packages/create-hops-app/lib/package-manager.js
packages/spec/integration/create-hops-app/__tests__/index.spec.js

npm@7 introduced new behaviour for peer dependencies and installs them
automatically.
Unfortunately this breaks our integration tests because
react-helmet-async does not yet support react@17.
With this commit we add a CLI flag for the npm install command to force
npm to switch back to the previous behaviour to not automatically
install peer dependencies.
We can remove this again once react-helmet-async support react@17.
<details>
| Syntax | …

Force npm legacy peer dependency handling in create-hops-app

---

bors.toml

Ref: https://github.com/bors-ng/bors-ng/issues/730
<details>
| --- | --- |
| bors delegate=[list] | Allow …

chore: use correct status name in bors config

---

packages/webpack/lib/configs/node.js

We target the currently running Node.js version as transpilation target
(unless configured explicitly), this leads to new syntax features left
untranspiled if the current Node.js version supports them.
Unfortunately webpack@4 uses an old version of acorn (parser), which
doesn't understand new syntax features added after ES2018.
<details>
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. Short …

Fix babel transpilation target (always transpile new syntax)

---

packages/bootstrap/lib/loader.js
packages/bootstrap/lib/resolver.js

Hops tries to load the package.json files of all direct dependencies to
try and figure out if the dependency is a Hops preset and should be
considered for the current config object.
This will break if the dependency that Hops tries to resolve doesn't
allow to access the package.json directly, for example by using the new
module specification "exports" field in their package.json.
This commit checks for that specific error and skips it.
<details>
| …

fix(bootstrap): do not try to resolve ESM packages for presets

---

packages/create-hops-app/lib/package-manager.js
packages/spec/integration/create-hops-app/__tests__/index.spec.js

picks #1432 
<details>
| --- | --- | …

Force npm legacy peer dependency handling in create-hops-app (v13)

---

packages/bootstrap/lib/loader.js
packages/bootstrap/lib/resolver.js
packages/webpack/lib/configs/node.js

Next release: Monday, November 30th
* [Fix babel transpilation target (always transpile new syntax) (#1439)](https://github.com/xing/hops/pull/1439)
* [fix(bootstrap): do not try to resolve ESM packages for presets (#1438)](https://github.com/xing/hops/pull/1438)
<details>
| --- | --- |
| bors merge- | Cancel an r+, r=, …

Prepare next Hops 13.x release

---

packages/webpack/lib/configs/node.js

Next release: Monday, November 30th
* [Fix babel transpilation target (always transpile new syntax) (#1439)](https://github.com/xing/hops/pull/1439)
<details>
| --- | --- |
| bors …

Prepare next Hops v12.x release

---

packages/spec/integration/typescript-styled-components/index.tsx
packages/spec/integration/typescript-styled-components/package.json
packages/spec/package.json
yarn.lock

...instead of failing with error message:
```
[tsl] ERROR in ./packages/spec/integration/typescript-styled-components/index.tsx(13,7)
TS2322: Type '{ children: string; css: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>'.
Property 'css' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>'.
```
<details>
| --- | --- …

chore(spec): make TS/styled-components example build (v13)

---

packages/react/render/mixin.server.js

Since mixinable always wraps async hooks in a promise [1] there is no
need for us to add another promise on top.
[1]: https://github.com/untool/mixinable/blob/master/src/index.js#L109
<details>
| --- | --- |
| …

refactor(react): reduce render promise chain by one promise

---

bors.toml

...to reflect the new name of the job, introduced with the update of Canarist v2.
<details>
| --- | --- | …

chore: update Bors config

---

bors.toml

...to reflect the new name of the job, introduced with the update of Canarist v2.
<details>
| --- | --- | …

chore: update Bors config (v13)

---

bors.toml

...to reflect the new name of the job, introduced with the update of Canarist v2.
<details>
| --- | --- | …

chore: update Bors config (v12)

---

DOCUMENTATION.md
packages/bootstrap/README.md
packages/development-proxy/README.md
packages/express/README.md
packages/webpack/README.md

docs: document available debug tags

---

DOCUMENTATION.md
packages/bootstrap/README.md
packages/development-proxy/README.md
packages/express/README.md
packages/webpack/README.md

docs: document available debug tags (v13)

---

packages/webpack/lib/utils/compiler-fork.js
packages/webpack/lib/utils/compiler.js

Previously we've registered an event handler for the 'message' event on
the IPC channel, which kept the forked process alive even when all its
work was done and we had to manually kill it.
Now we register the callback with `.once` which should cause the child
to exit when no other handles are blocking the event loop.
Through this, the bundle analyzer plugin works correctly because its
process isn't being called once the build finishes.
<details>
| …

fix(webpack): ensure forked compiler exits when done

---

packages/spec/helpers/env.js
packages/spec/helpers/test-helpers.js
packages/spec/integration/create-hops-app/__tests__/index.spec.js
packages/spec/integration/development-proxy/__tests__/object-config.js
packages/spec/integration/development-proxy/__tests__/string-config.js
packages/spec/integration/doctor/__tests__/build.js
packages/spec/integration/doctor/__tests__/develop.js
packages/spec/integration/graphql/__tests__/develop.js
packages/spec/integration/hops/__tests__/import-component-loading.js
packages/spec/integration/hops/__tests__/import-component-mocked.js
packages/spec/integration/jest-preset/__tests__/preset.js
packages/spec/integration/lambda/__tests__/build.js
packages/spec/integration/typescript-unit-testing/__tests__/index.js

This change makes it possible to disable Puppeteer in Hops's integration test suite on a per-test basis, by adding the following code comment at the top of the test file:
```js
/**
* @jest-hops-puppeteer off
*/
```
<details>
| --- | --- |
| bors try | Run the test suite …

chore(spec): add possibility to disable puppeteer for single tests

---

packages/bootstrap/lib/validator.js
packages/bootstrap/package.json
yarn.lock

...which aren't part of the main package anymore as of v7.
Removes the warning `unknown format "hostname" ignored in schema at path "#/properties/aws/properties/domainName"` for `hops-lambda`.
<details>
| --- | --- |
| bors try | Run the test suite without pushing to …

fix(bootstrap): add Ajv formats

---

packages/postcss/README.md
packages/postcss/mixin.core.js
packages/postcss/preset.js
packages/spec/integration/postcss/__tests__/build-static.js
packages/spec/integration/postcss/index.js
packages/spec/integration/postcss/package.json
packages/spec/integration/postcss/styles.css
packages/spec/package.json
yarn.lock

1.) Changes the export syntax of CSS Modules from CommonJS to ESM, which is a **Breaking Change**.
2.) Adds option, to export named exports from CSS Modules
<details>
| --- | --- | …

feat: change CSS Modules export syntax

---

packages/spec/helpers/env.js
packages/spec/helpers/test-helpers.js
packages/spec/integration/development-proxy/__tests__/object-config.js
packages/spec/integration/development-proxy/__tests__/string-config.js
packages/spec/integration/doctor/__tests__/develop.js
packages/spec/integration/graphql-mock-server/__tests__/develop.js
packages/spec/integration/graphql-no-ssr/__tests__/develop.js
packages/spec/integration/graphql/__tests__/develop.js
packages/spec/integration/hot-module-reload/__tests__/develop.js
packages/spec/integration/postcss/__tests__/build-static.js
packages/spec/integration/postcss/__tests__/build.js
packages/spec/integration/postcss/__tests__/develop.js
packages/spec/integration/pwa/__tests__/build.js
packages/spec/integration/react/__tests__/develop.js
packages/spec/integration/redux-without-ssr/__tests__/develop.js
packages/spec/integration/redux/__tests__/develop.js
packages/spec/integration/styled-components/__tests__/develop.js
packages/spec/integration/typescript-styled-components/__tests__/develop.js
packages/spec/integration/typescript/__tests__/develop.js
packages/spec/package.json

supersedes #1470 
Not that much changes here, but running the `start`-command got decoupled from retrieving the URL. And retrieving the URL got decoupled from retrieving the function for stopping the server.
Also the values, the `build`-command resolves to, now reflects what `exec` is yielding.
<details>
| --- | --- |
| …

chore(spec): refactor HopsCLI

---

.github/workflows/node-ci.yml
packages/jest-environment/helpers.js
packages/spec/package.json

chore: run eslint in CI

---

packages/postcss/mixin.core.js

`postcss-loader@4` introduced [the feature of collecting & merging all
the `postcss.config.js`-files](https://www.npmjs.com/package/postcss-loader/v/4.0.0#config) of a project (even of external ones in the
`node_modules`-folder) and take them into account, when processing CSS.
This has not been in the scope of `hops-postcss` and thus needs to be
deactivated.
<details>
| --- | --- |
| bors merge | Run the test suite and push …

fix(postcss): disable external PostCSS configs

---

packages/jest-environment/README.md

docs(jest-environment): remove superfluous await statement

---

.github/check-label.yml

chore: add config for check-label bot

---

.github/release-bot.yml

chore: add config for release-bot

---

packages/bootstrap/lib/utils.js
packages/bootstrap/package.json
yarn.lock

According to lodash docs (https://lodash.com/per-method-packages) the
per method packages shouldn't be used any longer.
The bootstrap code of hops is also bundled in the client and is
therefore directly related to the described problem.

refactor: correct lodash import

---

packages/webpack/mixins/develop/mixin.core.js
yarn.lock

fix: disable native Webpack stats in develop-mode

---

renovate.json

Not sure about the cherry-picking, though. 
<details>
| --- | --- | …

chore: have Renovate set PR labels for base branch

---

package.json
renovate.json

chore: pin version of react-apollo in canarist runs

---

renovate.json

Takes care of resolution introduced in #1532 
<details>
| --- | --- | …

chore: have Renovate update pinned version of react-apollo

---

renovate.json

chore: configure renovate to create PRs against release-pr branches

---

packages/react-apollo/README.md

This pull request fix two links for apollographql documentation

docs: apollo documentation links

---

.github/workflows/release.yml

chore: configure release bot as author for automatic releases

---

.github/workflows/release.yml

chore: use custom github token to push release notes

---

.github/workflows/publish.yml

chore: add publish action to push tags and publish to registry

---

.github/release-bot.yml
package.json

chore: add release preparation command

---

package.json

chore: fix prepare release command

---

.github/workflows/publish.yml

...by fetching enough commits to do a diff between the current and the
previous HEAD.
<details>
| --- | --- |
| bors delegate+ | Allow the pull request author to merge their …

chore: fix changelog creation in publish action

---

.github/workflows/publish.yml

chore: install & cache Node dependencies in Publish Action

---

.github/workflows/publish.yml

chore: fix retrieving the latest change on the CHANGELOG

---

package.json

chore: have canarist test against internal release PR branch

---

.github/workflows/node-ci.yml
bors.toml
package.json

...because it is not actively maintained and blocks us by causing failing tests in CI.
<details>
| --- | --- |
| bors delegate+ | Allow the pull request author to merge their …

chore: remove foosbyte/kicker-trainer from canarist tests

---

.github/workflows/publish.yml

`lerna publish from-git` is what we want to do. Unfortunately though there's a merge commit done by the bors-bot between `lerna version` and `lerna publish`.
So when lerna does `git diff-tree --name-only --no-commit-id --root -r -c HEAD` to detect the packages it needs to publish, it doesn't find any on the merge commit.
The solution is to detect the release commit done during `lerna version` and check out that one. Then the git tag created in the publish-Action references the correct commit. And `lerna publish from-git` actually finds packages to publish.
Still feels a little dirty, though… :grimacing:
<details>
We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a …

chore: check out release commit before publishing

---

.github/workflows/publish.yml

chore: write npm token into .npmrc

---

.github/workflows/publish.yml

because the built-in GITHUB_TOKEN does not allow to push to workflow
files.
<details>
| --- | --- |
| bors …

chore: use GH_TOKEN to push tags and releases

---

.github/workflows/publish.yml

although the npm docs recommend not doing this, because the npm cli
automatically replaces the NPM_TOKEN variable from the environment,
the library used here (libnpmpublish) doesn't seem to be able to, so we
need to actually write the token.
- https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow
- https://github.com/lerna/lerna/issues/2404
<details>
| --- | --- |
| bors merge | Run the test suite and push to …

chore: write npm token directly into .npmrc file

---

.github/workflows/delete-merged-branches.yml

...instead of using the built-in Github feature for that. So we can make sure,
that our release PR branches never get deleted, which again ensures, that the
Renovate PRs targetting them don't get re-based after a release PR is
merged.
<details>
| --- | --- |
| bors try | …

chore: use action for deleting branches of closed PRs

---

.github/workflows/publish.yml

The `npm/v1/user` endpoint is not accessible for npm automation tokens
and since we are using an automation token, we need to disable the lerna
access verification before publishing.
- https://github.com/lerna/lerna/issues/2788
<details>
| --- | --- |
| bors try | Run …

chore: do not verify npm access before publishing

---

bors.toml

...so the dedicated GH Action can do it.
<details>
| --- | --- |
| bors delegate=[list] | Allow the listed …

chore: prevent bors-bot from deleting branches

---

packages/bootstrap/lib/__tests__/utils.test.js
packages/bootstrap/lib/utils.js
packages/bootstrap/package.json
yarn.lock

To reduce our bundle size by about 10kb we replace lodash.mergeWith with
a custom implementation to merge objects and arrays.
<details>
| --- | --- |
| bors delegate+ | Allow the …

refactor(bootstrap): replace lodash.mergeWith with custom function

---

packages/bootstrap/lib/__tests__/utils.test.js
packages/bootstrap/lib/config.js
packages/bootstrap/lib/loader.js
packages/bootstrap/lib/utils.js
packages/webpack/lib/utils/loader.js

There's no way anymore to make Hops resolve mixins in the opposite order
than the configs. Mixins and configs will now always be resolved in the same
order and thus be consistent in the way they overwrite previous presets.
**BREAKING CHANGE**: the config option `enableLegacyMixinSortOrder` has been removed.
<details>
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. Short for "reviewed: looks …

fix: remove mixin-order escape hatch

---

DOCUMENTATION.md
packages/info/doctor/mixin.core.js
packages/info/doctor/validators/duplicates.js

**BREAKING CHANGE**: Hops now requires strictly de-duplicated packages
⚠️ We'll have to pin the versions on the soon to be created `v14.x`-branch and then do the release. :warning:
<details>
| --- | --- |
| …

Require strictly aligned Hops packages

---

packages/info/doctor/mixin.core.js
packages/info/package.json
packages/lambda/mixin.core.js
packages/react-apollo/mixin.core.js

As of now, `hops-info` only handles warnings and errors, that have been passed
into the respective `pushWarning` or `pushError` functions, which again come as
arguments into the `diagnose`-hook.
Strings — or arrays of strings —, returned from the `diagnose`-hook,
aren't handled anymore.
**BREAKING CHANGE**: hops-info does not handle warnings returned from the `diagnose`-hook anymore.
<details>
| --- | --- |
| bors merge | …

fix(info): remove deprecated handling of warning messages

---

packages/spec/package.json

This should close #1660 and #1661
<details>
| --- | --- |
| bors delegate=[list] | Allow the listed users …

chore(spec): use version range for styled-components types in tests

---

packages/webpack/package.json
yarn.lock

Otherwise the change made in [`33a060b`](https://github.com/xing/hops/commit/33a060b191d94822c5d0868782c1c6cbdc88b8a5) would
potentially be breaking.
FYI: I'll cherry-pick this commit and the referenced one onto `v13.x` manually.
<details>
| --- | --- |
| bors try | Run …

chore(webpack): raise version of webpack-dev-middleware

---

packages/postcss/README.md
packages/postcss/mixin.core.js
packages/postcss/preset.js
packages/spec/integration/postcss/index.js
packages/spec/integration/postcss/other-styles.css

This reverts the breaking change introduced with [`5f4ff80`](5f4ff80#diff-f6674fc8d197d1faca718594bf4931825ac8c5b1ba7aa51d523d3e0fd0a50633).
It also renders the previously introduced preset option `namedExport`
obsolete.
Switching to ESM has been a bold move and it turned out, that it not
only has the potential to break existing Hops apps through their own
CSS. But also through third-party packages, that themselves import CSS
Modules in their code. In unfortunate cases they may be using
namespace imports, while they're actually not able to be switched to
named exports, because of reserved keywords in their CSS classnames or
duplicate class names after camelCasification.
In those situations, the third-party package would not be usable.
However, by sticking with CommonJS as a module type …

fix(postcss): use module type "commonjs"

---

packages/webpack/mixins/develop/mixin.core.js
packages/webpack/package.json
yarn.lock

picks #1513, at least the interesting part.
<details>
| --- | --- | …

fix(webpack): disable native Webpack stats in develop-mode

---

DOCUMENTATION.md

docs: add missing peer-deps of jest-preset-hops

---

lerna.json

chore: set lerna exact flag to release with strict dependencies

---

packages/template-graphql/package.json
packages/template-react/package.json
packages/template-redux/package.json

A recent change renamed the entry files for the templates from `.js` to
`.jsx` which caused the entry files to not be found anymore.
<details>
| --- | --- |
| bors delegate+ | Allow …

fix: set correct "main" fields for templates

---

packages/info/README.md
packages/info/package.json
packages/info/preset.js
packages/info/web-vitals/mixin.browser.js
yarn.lock

This adds a new render option `webVitals` to which a `ReportHandler`
can be passed via `webVitals.handler`.
The handler will be called for each of the three core web vitals:
- CLS (cumulative layout shift)
- FID (first input delay)
- LCP (largest contentful paint)
<details>
| --- | --- |
| bors merge- | Cancel an r+, r=, …

feat: add web vitals support

---

packages/bootstrap/lib/validator.js

fix(bootstrap): adapt validator to breaking changes in ajv

---

packages/react/fast-refresh/mixin.core.js
packages/webpack/mixins/develop/mixin.core.js

Wait for #1720 and add `--fast-refresh`, too.
<details>
| --- | --- | …

fix: add missing CLI-flags to develop command

---

packages/spec/helpers.js

chore(spec): remove superfluous warning checks

---

packages/react/import-component/context.js
packages/react/import-component/index.js

The import component context should be initialized with undefined,
as this is the expected behavior of the Import Component.
Closes #1729

fix: correctly initialize import component context

---

.github/canarist-service.yml
.github/workflows/node-ci.yml
CONTRIBUTING.md

..., namely the main- & the release branches
<details>
| --- | --- | …

chore: skip tests on certain branches

---

packages/bootstrap/package.json
packages/express/package.json
packages/webpack/package.json
yarn.lock

chore: remove superfluous dependency

---

package.json
packages/apollo-mock-server/package.json
yarn.lock

...manually, because the Apollo team published the v2.12.x packages with tag `next`,
so Renovate will not bother to create an update PR for us.
<details>
| --- | --- |
| bors …

fix(apollo-mock-server): update package graphql-tag

---

packages/react-apollo/mixins/apollo3/mixin.browser.js

This fix re-enables the configuration of a custom apollo cache.

fix: allow custom apollo cache

---

renovate.json

refs #1783
<details>
| --- | --- | …

chore: fix Renovate config

---

renovate.json

…which is: relying on the lockfile maintenance.
When I updated the config to switch to the new configuration properties, I
failed to re-create the setting for dev-dependencies¹, which led to a
lot of PRs being opened by Renovate.
With this change the majority of dependency updates should be done
implicitly again via the lockfile maintenance. Only major updates will
lead to a dedicted PR which replaces the version string with the newer
one.
----
¹: https://github.com/xing/hops/blob/dad6ee42a1d80dcccb47c587c61ebeb02ea2a819/renovate.json#L40-L42
<details>
We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members …

chore: restore old range strategy for dev-dependencies

---

.github/release-bot.yml
package.json

chore: add comand to roll back release commit

---

renovate.json

closes #1819
<details>
| --- | --- | …

chore: use replace-strategy for prod-deps, too

---

packages/debug/browser.js

fix(debug): provide method extend in the browser

---

packages/jest-preset/jest-preset.js

...to `jsdom`. This is a prerequisite for the upgrade to Jest 27, which
changes its default test environment to `node`.
<details>
| --- | --- |
| bors delegate+ | Allow the pull …

fix(jest-preset): set Jest test environment explicitly

---

package.json
packages/jest-environment/package.json
packages/jest-preset/jest-preset.js
packages/jest-preset/package.json
packages/jest-preset/transforms/babel.js
packages/template-graphql/package.json
packages/template-react/package.json
packages/template-redux/package.json
yarn.lock

The Canarist tests aren't helpful here, because the dependency tree of the Canarist test monorepo contains both Jest v26 & Jest v27 packages. This won't work.
closes #1760 #1761 #1831 #1832 #1838 #1839
<details>
| --- | --- |
| bors try | Run the test suite without …

feat: update Jest to version 27

---

package.json
packages/jest-preset/package.json
packages/template-graphql/package.json
packages/template-react/package.json
packages/template-redux/package.json
yarn.lock

...in order to get rid of the error...
```
Error: [BABEL]: Reentrant plugin detected trying to load "fea/hops/node_modules/jest-preset-hops/helpers/babel-plugin-rename-corejs.js". This module is not ignored and is trying to load itself while compiling itself, leading to a dependency cycle. We recommend adding it to your "ignore" list in your babelrc, or to a .babelignore. (While processing: fea/hops/node_modules/jest-preset-hops/helpers/babel-plugin-rename-corejs.js)
```
...when the Jest cache is warmed
<details>
We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members of this repository with push access) and …

chore: downgrade Jest to version 26

---

package.json

...in order to fix the tests
<details>
| --- | --- |
| bors delegate=[list] | Allow the listed users to r+ …

chore: set Jest resolution for Canarist test

---

packages/postcss/mixin.core.js
packages/postcss/package.json
packages/pwa/lib/service-worker-plugin.js
packages/pwa/mixin.core.js
packages/pwa/package.json
packages/typescript/package.json
packages/webpack/lib/configs/build.js
packages/webpack/lib/configs/develop.js
packages/webpack/lib/configs/node.js
packages/webpack/lib/plugins/log.js
packages/webpack/lib/plugins/stats.js
packages/webpack/lib/utils/compiler-fork.js
packages/webpack/lib/utils/compiler.js
packages/webpack/mixins/build/mixin.core.js
packages/webpack/package.json
yarn.lock

<table>
<tr>
<th>webpack v4</th>
<th>webpack v5</th>
</tr>
<tr>
<th colspan="2">Build artifacts</th>
</tr>
<tr>
<td>
<ul>
<li>server.js (3.85 MB)</li>
<li>fixture-react-0-84e0870c4c53.js (1.76 MB)</li>
<li>fixture-react-1-1aa9acadc44c.js (4.88 kB)</li>
<li>fixture-react-2-b6061799b9cf.js (1.2 kB)</li>
<li>fixture-react-3-417ead29afb3.js (1.39 kB)</li>
<li>fixture-react-31cd1819b262.js (158 kB)</li>
<li>img-7507deb7dbbf6284.png (235 B)</li>
</ul>
</td>
<td>
<ul>
<li>server.js (3.76 MB)</li>
<li>fixture-react-8da4f12103b1.js (1.71 MB)</li>
<li>fixture-react-9069381437d1.js (150 kB)</li>
<li>fixture-react-3-8981672b56c9.js (3.79 kB)</li>
<li>fixture-react-4-bd71fc8886d1.js (968 B)</li>
<li>fixture-react-2-588fcf498ae0.js (919 B)</li>
<li>img-7507deb7dbbf6284.png (235 B)</li>
</ul>
</td> …

feat: update webpack to v5

---

packages/webpack/lib/configs/build.js
packages/webpack/lib/configs/develop.js

...in order to make the non-Babel-transpiled webpack boilerplate code work in older browsers
<details>
| --- | --- |
| bors delegate+ | Allow the pull request author to merge their …

fix(webpack): target ES5 for browser builds

---

packages/bootstrap/index.js
packages/webpack/README.md
packages/webpack/lib/configs/build.js
packages/webpack/lib/configs/develop.js
packages/webpack/lib/configs/node.js
packages/webpack/mixins/config/mixin.core.js

- with cold webpack cache: ~6.3s
- with warm webpack cache: ~2.3s
<details>
| --- | --- |
| bors …

feat(webpack): enable filesystem-based caching

---

packages/create-hops-app/lib/package-manager.js
packages/spec/integration/create-hops-app/__tests__/index.spec.js
packages/spec/package.json
yarn.lock

…and add intermediary support for Node v16
<details>
| --- | --- | …

chore(spec): improve create-hops-app test

---

packages/create-hops-app/lib/package-manager.js

…for introducing support for Node 16
<details>
| --- | --- |
| bors delegate=[list] | Allow the listed …

fix(create-hops-app): remove intermediary hack

---

packages/msw/integration.js
packages/msw/package.json

refactor(msw): get rid of url-join

---

packages/msw/integration.js
packages/msw/mixin.core.js

fix(msw): rename /_mocks/ endpoint to /_msw/ to avoid clashes

---

packages/jest-preset/setup-msw.js
packages/msw/README.md
packages/msw/index.d.ts
packages/msw/index.js
packages/msw/mixin.browser.js
packages/msw/mixin.core.js
packages/msw/mixin.server.js
packages/msw/package.json
packages/msw/preset.js
packages/msw/unit.d.ts
packages/msw/unit.js
packages/template-graphql/mocks.js
packages/template-graphql/package.json
packages/template-graphql/src/app.jsx
packages/template-graphql/src/home/spec/index.spec.jsx

feat(msw): allow to specify a handlers file to use during development

---

packages/apollo-mock-server/README.md
packages/config/README.md
packages/create-hops-app/README.md
packages/debug/README.md
packages/development-proxy/README.md
packages/express/README.md
packages/graphql/README.md
packages/hops/README.md
packages/jest-environment/README.md
packages/jest-preset/README.md
packages/lambda/README.md
packages/mixin/README.md
packages/msw/README.md
packages/postcss/README.md
packages/pwa/README.md
packages/react-apollo/README.md
packages/react/README.md
packages/redux/README.md
packages/styled-components/README.md
packages/template-graphql/README.md
packages/template-react/README.md
packages/template-redux/README.md
packages/typescript/README.md

docs: let all links to "main readme" point to readme version selection

---

packages/bootstrap/__tests__/environmentalize.test.js
packages/bootstrap/__tests__/index.test.js
packages/bootstrap/lib/utils.js

This pull request closes issue #1156
Whitelisting a full object does not work
this PR fixes whitelisting in `browserWhitelist` to enable
whitelisting of full objects.
- [] Documentation has been added
<details>
| --- | --- |
| bors try | Run the test suite without …

Nested props

---

packages/bootstrap/__tests__/environmentalize.test.js

This PR improves test coverage and verifies and documents functionality provided by environmentalize
missing tests for several features
adds tests to cover features
<details>
| --- | --- |
| bors try- | Cancel …

test(bootstrap): add more test-coverage

---

packages/msw/README.md
packages/msw/mixin.browser.js
packages/msw/mixin.core.js
packages/msw/mixin.server.js
packages/msw/preset.js

fix(msw): remove enableMockServiceWorker configuration option

---

packages/webpack/lib/middlewares/render.js
packages/webpack/lib/utils/compiler.js
packages/yargs/mixin.core.js

This commit fixes the global Hops error handler `handleError`, which
should exit the process, when the second arugment is `false`.
Unfortunately when a `truthy` value is passed it doesn't exit, so now
we strictly check for the value `true`.
We also catch errors of the forked webpack compiler and exit the main
process when they are not recoverable.
<details>
| --- | --- |
| bors merge | Run the test suite and push to master …

fix: exit Hops on unrecovrable webpack errors

---

packages/info/logger/index.js
packages/styled-components/mixin.core.js
packages/yargs/mixin.core.js

This commit enables a filesystem based logging, which can be enabled by
setting the environment variable `HOPS_LOG_LOCATION` to a writable
directory (for example `HOPS_LOG_LOCATION=$(pwd)`).
If the directory is writable by the current user Hops will write all log
messages into a `hops-log.txt` in that directory.
This is useful in cases the stdout/stderr logs are not accessible,
for example when running with docker-compose on a CI server.
<details> …

Fs logging

---

packages/jest-preset/setup-msw.js

this fixes an issue with babel-jest where on jest 27.x the
transpile would fail because of the imprt statement
<details>
| --- | --- |
| bors delegate+ | Allow the pull request …

change import statement to require

---

packages/info/logger/index.js

fix(info): test if logLocation is writable

---

packages/yargs/index.js
packages/yargs/mixin.core.js

this fixes a setup where `process.uncaught*` handlers where
passing objects into our error handlers. in certain cases the
logic would exit the hops app, even when no exit is required, i.e.
when a middleware would crash.
Co-authored-by: Björn Brauer <bjoern.brauer@new-work.se>
Co-authored-by: Jonas Holland <jonas.holland@new-work.se>
<details>
| --- | --- |
| …

fix: do no exit hops in certain cases

---

packages/webpack/lib/configs/build.js
packages/webpack/lib/configs/node.js

we saw a behaviour with dynamic imports for SSR, when the import
was directly referenced, e.g. with `import(./foo')` instead of
`import('./')` webpack would with create different filehashes in
the moduleMap when the option `usedExports` is enabled.
filenames before hashing in webpack with `usedExports` followed the
pattern: `filename.js|abc`
filenames without `usedExports` are simply the filename: `filename.js`
they are then hashed in webpacks `HashedModuleIdsPlugin.js` with
different results, leading to an incomplete modulesMap
Co-authored-by: Jonas Holland <jonas.holland@new-work.se>
<details>
We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our …

fix: create same hashes on server and client

---

.github/workflows/node-ci.yml
bors.toml

Transitive dependencies (namely `@npmcli/fs`) dropped support for
Node.js v15, which means Hops can't be used with Hops 15 anymore.
We could potentially downgrade the `terser-webpack-plugin`, but we
decided against that, because we don't want to remove features in Hops
just because it stopped working with an unmaintained non-lts version.
<details>
| --- | --- |
| bors merge | Run the test suite and push to master if it …

chore: disable Node.js v15 tests

---

packages/webpack/lib/plugins/log.js

Example:
```
hops-demo:warning Should not import the named export 'config' (imported as 'config') from default-exporting module (only default export is available soon) (../../../../node_modules/something/main.js:8:4-10)
hops-demo:warning Critical dependency: the request of a dependency is an expression (./src/main.js:36:0-12)
```
<details>
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. …

fix(webpack): print file name and location in webpack warnings

---

packages/webpack/lib/configs/node.js
packages/webpack/lib/utils/compiler.js

For some reason we see intermittent failures with the source-map-support
package (examples: https://github.com/evanw/node-source-map-support/issues/252
and https://github.com/evanw/node-source-map-support/issues/93).
The fix that worked for us seems to be to externalize the source-map.
<details>
| --- | --- |
| bors merge- …

fix(webpack): externalize server source-map to prevent RangeError

---

package.json
packages/graphql/package.json
packages/react-apollo/package.json
packages/spec/package.json
packages/template-graphql/package.json
renovate.json
yarn.lock

Pin `@apollo/client` to `3.4.17` because of a bug in the SSR implementation of `useLazyQuery`.
https://github.com/apollographql/apollo-client/issues/9108
Also, clean up leftovers from `react-apollo` for which we have removed support in Hops 15.
<details>
| --- | --- |
| …

Fix apollo

---

package.json

chore: let canarist test against internal master

---

bors.toml
package.json

The internal-workshop repository hasn't been used/updated for a while
and causes dependency issues.
Since the tests in the workshop repository are focused on teaching
testing and are quite few, I don't think they offer much benefit over
the existing tests in internal-hops.
Therefore I'm disabling the internal-workshop canarist tests.
<details>
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. …

chore: remove internal-workshop project from canarist

---

packages/react/import-component/babel.js

We're using base64 to generate short chunk names, unfortunately this
means that we need to replace some characters which are invalid
characters in file names.
We replace `/` with `-`, `+` with `_` and `=` with an empty string.
Replacing `=` with an empty string shouldn't occur in real life,
because we're only using the first four characters.
<details>
| --- | --- |
| bors merge | Run the test suite and push to master if it …

fix(react): replace invalid characters in chunk name
