app/src/style.css
package.json

Adds a dependency for the package [postcss-modules-values](https://www.npmjs.com/package/postcss-modules-values) so the user can define and share variables between components inside the app.
**Open question:** 
Would it be good to add more of the logic this package offers to the example app so we can also test the css output?

Adds postcss-modules-values

---

app/src/main.js

We still need to discuss if we want to talk about "stateless" component
in the first part. Any suggestions?
Closes #5.

Annotates template source code

---

app/src/style.css
app/src/values.css

Please let me know if any of you would be interested in seeing more examples from the [CSSnext features list](http://cssnext.io/features/) or have any suggestion.

Adds some CSSnext syntax examples and imports external values

---

etc/webpack.base.js
lib/config.js
lib/render.js

```noBabel``` sounds like an option requiring a boolean, I'm proposing ```babelIgnore``` as a more descriptive option name.

Renames 'noBabel' config option to a more descriptive 'babelIgnore'

---

etc/webpack.base.js

Adding support for jsx files for the ones who would like to have it.

Adding support for jsx files

---

etc/webpack.test.js

ignoring tmp files for linting

---

plugin/index.js

Prefix all script and stylesheet paths with asset path prefix based on webpack output.publicPath config.

template generation with asset path prefix

---

package.json
plugin/index.js

refactor and vastly simplify plugin, replace custom code with existing npm modules
@robin-drexler PTAL :)

Refactor Plugin

---

demo/package.json
demo/src/app.js
demo/src/browser.js
demo/src/server.js
package.json

update dependencies, especially for demo

Release 4.0.6

---

changelog.md
package.json
plugin/index.js
spec/transpiler.js
transpiler/index.js

refactoring, removal of `close` method

Release 5.0.0

---

package.json
packages/config/loaders/babel.js
packages/config/package.json

https://webpack.js.org/guides/code-splitting-async/#usage-with-babel

feat(hops-config): allow to use imports() for dynamically requiring chunks

---

demo/package.json
demo/src/app.js
package.json
packages/cli/package.json
packages/config/configs/build.js
packages/config/configs/develop.js
packages/config/configs/node.js
packages/config/index.js
packages/config/lib/postcss-necsst.js
packages/config/loaders/file.js
packages/config/package.json
packages/middleware/package.json
packages/plugin/package.json
packages/react/dom.js
packages/react/node.js
packages/react/package.json
packages/redux/basic.js
packages/redux/package.json
packages/renderer/package.json
packages/root/package.json
packages/server/lib/common.js
packages/server/package.json
packages/transpiler/package.json

This introduces `assetPath` and `basePath` configs to generate asset and html files in separate folders within `buildDir`.

Release 6.0.0 beta 11

---

package.json
packages/cli/readme.md

This adds a readme to the hops-cli package.

docs(hops-cli): add readme

---

packages/react/dom.js

fix hmr for react, i.e. actually unmout before rerendering

---

packages/config/configs/build.js

Fix Safari/iOS Browser build error

---

packages/jest-preset/README.md
packages/jest-preset/package.json

* `jest-preset-hops` package lacks required transform files
* README has some wrong wording
* missing files are added to published package
* README is fixed

Fix jest preset

---

packages/build/commands/build.js
packages/build/commands/develop.js
packages/express/commands/serve.js
packages/graphql/commands/graphql.js
packages/local-cli/commands/start.js

By lazy-requiring the command implementations we can increase the CLI
start-up performance.

perf: lazy-require command implementations

---

README.md
packages/graphql/README.md
packages/react/README.md
packages/redux/README.md

Currently, our READMEs are, in places, incomplete and outdated.
In this PR, we want to start improving the READMEs in these regards.

Improve Readmes

---

packages/transpiler/README.md

This is in preparation of #323 
Please merge and publish this PR first, followed by #323

(1/2) chore(transpiler): deprecate package

---

lerna.json

Lerna fails to write proper commit messages. 
With this PR, it actually does.

build: make lerna write proper commit messages

---

packages/lambda/cloudformation.yaml
packages/lambda/deploy.js
packages/lambda/destroy.js

This PR makes the CloudFormation template region independent and
refactors the deployment code to remove obsolete references.

Lambda CF improvements (region independence, cleanup)

---

packages/graphql/node.js

feat(graphql): disable data fetching in static ssr

---

README.md

This PR tries to better reveal what the core philosophy of Hops is while making Readme as concise as possible

Revised Philosophy

---

README.md
docs/Home.md
package.json

Add GitHub wiki as a subtree

---

packages/build-config/configs/build.js
packages/build-config/configs/develop.js
packages/build-config/package.json
packages/build-config/plugins/webpack-service-worker.js
packages/build-config/sections/module-rules.js
packages/build-config/sections/module-rules/webmanifest.js
packages/build-config/sections/resolve.js
packages/build-config/shims/worker-shim.js
packages/config/index.js
packages/pwa/dom.js
packages/pwa/node.js
packages/pwa/package.json
packages/pwa/worker.js
packages/spec/config.js
yarn.lock

This is an alternative approach to #375

Alternative approach to Service Workers

---

yarn.lock

Merging this will unblock #399

chore: recreate yarn.lock to get latest dependency updates

---

renovate.json

See: https://renovateapp.com/docs/configuration-reference/configuration-options#lockfilemaintenance

chore: enable renovate lock file maintenance

---

packages/react/node.js

This allows applications to always add headers
THIS IS A BREAKING CHANGE

fix(react): always respect headers, even on a miss

---

packages/build-config/lib/check-esnext.js
packages/build-config/sections/resolve.js

due to issues in webpack such as https://github.com/webpack/webpack/issues/7032

fix(build-config): remove mjs support when resolving files

---

packages/react/__tests__/__snapshots__/node.spec.js.snap
packages/react/lib/template.js

This reverts commit 678f2f4f5cec0276d3e6bf822f601662b8b6d8c1.

Revert "refactor(react): load scripts async"

---

packages/config/package.json
packages/express/package.json
packages/hops-preset-defaults/package.json
packages/postcss/package.json
packages/react/mixin.server.js
packages/react/package.json
packages/redux/actionCreatorDispatcher/mixin.server.js
packages/redux/mixin.server.js
packages/redux/package.json
packages/webpack/package.json
yarn.lock

Renaming due to: https://github.com/untool/untool/pull/53

Upgrade untool

---

packages/react/index.js
packages/react/lib/components.js
packages/react/mixin.core.js
packages/react/mixin.server.js
packages/react/preset.js
packages/react/server-data/context.js
packages/react/server-data/mixin.runtime.js
packages/react/server-data/withServerData.js

feat(react): add server data HOC

---

packages/cli/lib/run.js
packages/cli/package.json
yarn.lock

add support for https://github.com/motdotla/dotenv

support dotenv

---

packages/redux/README.md
packages/redux/mixin.browser.js
packages/redux/mixin.server.js
packages/redux/package.json
packages/spec/integration/redux/__tests__/develop.js
packages/spec/integration/redux/index.js
packages/spec/integration/redux/mixin.core.js
packages/spec/integration/redux/package.json

feat(redux): add fetch to thunks

---

packages/cli/package.json
packages/config/package.json
packages/express/package.json
packages/graphql/package.json
packages/jest-preset/package.json
packages/lambda/package.json
packages/postcss/package.json
packages/preset-defaults/package.json
packages/pwa/package.json
packages/react/package.json
packages/redux/package.json
packages/styled-components/package.json
packages/typescript/package.json
packages/webpack/package.json

_This is a template. Feel free to remove the parts you do not need! Start with this line, for example_ :wink:

chore: remove "files" from all package.json files

---

packages/graphql/lib/fragments.js
packages/graphql/package.json

_This is a template. Feel free to remove the parts you do not need! Start with this line, for example_ :wink:

refactor(graphql): replace pify with native util.promisify

---

packages/cli/lib/init.js

Print contextual getting started message based on availability of Hops
global CLI, yarn or npm.

fix(cli): print getting started message based on availability of CLI

---

packages/graphql/__tests__/dom.spec.js
packages/graphql/__tests__/node.spec.js
packages/graphql/mixin.browser.js
packages/graphql/mixin.server.js

fix(graphql): APOLLO_IQRD and APOLLO_IRQD to APOLLO_FRAGMENT_TYPES

---

packages/lambda/lambda.js
packages/lambda/lib/aws-config.js

This pull request closes issue #608

Fix hops-lambda URL

---

packages/config/package.json
packages/jest-preset/package.json
packages/jest-preset/transforms/babel.js
packages/lambda/package.json
packages/mixin/package.json
packages/postcss/package.json
packages/preset-defaults/package.json
packages/pwa/package.json
packages/react/mixin.core.js
packages/react/package.json
packages/spec/integration/jest-preset/__tests__/preset.js
packages/spec/integration/jest-preset/__tests__/setup/calculator-flow.js
packages/spec/integration/react/FlowText.js
packages/spec/integration/react/__tests__/develop.js
packages/spec/integration/react/index.js
yarn.lock

There is an issue with flow and class properties where values are undefined when they should not
babel/babel#8417
Fixes failing tests when flow is used

Fix flow integration

---

README.md

docs: add configureBuild hook to faq

---

README.md

This pull request closes issue # 620
According to discussion #620 I added one line to the `README.md` to clarify the way presets work.

docs: clarify presets configuration.

---

README.md
packages/cli/README.md
packages/config/README.md
packages/development-proxy/README.md
packages/express/README.md
packages/graphql/README.md
packages/jest-preset/README.md
packages/lambda/README.md
packages/mixin/README.md
packages/postcss/README.md
packages/preset-defaults/README.md
packages/pwa/README.md
packages/react/README.md
packages/redux/README.md
packages/styled-components/README.md
packages/template-graphql/README.md
packages/template-minimal/README.md
packages/template-react/README.md
packages/template-redux/README.md
packages/typescript/README.md
packages/webpack/README.md

This PR adds Gitter.im chat, npm version (tag next) and build status for
the master branch.

chore: update badges to show gitter chat, build status and npm version

---

packages/lambda/lambda.js
packages/lambda/lib/aws-config.js
packages/lambda/package.json
packages/spec/integration/lambda/__tests__/build.js
packages/spec/integration/lambda/index.js
packages/spec/integration/lambda/package.json

This PR fixes a couple of issues for hops-lambda which is at the moment
unusable.
It also adds a very basic integration tests to verify that bundling and
starting of the server works as expected.

Fixes Lambda issues

---

packages/postcss/mixin.core.js
packages/spec/integration/postcss/__tests__/build.js
packages/spec/integration/postcss/__tests__/develop.js
packages/spec/integration/postcss/global.css
packages/spec/integration/postcss/index.js
packages/spec/integration/postcss/styles.css
packages/spec/package.json
yarn.lock

fix(postcss): re-introduce global CSS support

---

packages/config/README.md
packages/create-hops-app/README.md
packages/development-proxy/README.md
packages/express/README.md
packages/graphql/README.md
packages/hops/README.md
packages/jest-preset/README.md
packages/lambda/README.md
packages/mixin/README.md
packages/postcss/README.md
packages/pwa/README.md
packages/react/README.md
packages/redux/README.md
packages/styled-components/README.md
packages/template-graphql/README.md
packages/template-react/README.md
packages/template-redux/README.md
packages/typescript/README.md

Main readme is intentionally left out as this is tackled in another PR. :)

Prepare docs for `latest` release

---

README.md

docs: restructure main readme

---

README.md

This pull request closes issue #802

docs: Add example for passing data from server to component

---

.gitignore
packages/spec/integration/graphql/fragmentTypes.json

This fixes an issue where our tests were failing because we had errors in the browser console.
https://travis-ci.org/xing/hops/builds/521624353
**Edit:** What I don't understand is, why we haven't seen this issue before though..

Add fragment types

---

.travis.yml
package.json
yarn.lock

This is a continuation of #882

Configure commitizen and enable commitlint

---

package.json

...to ensure there will be a changelog pushed to Github.

chore: check for GH_TOKEN before a release

---

packages/config/package.json
packages/graphql/package.json
packages/hops/package.json
packages/lambda/package.json
packages/mixin/package.json
packages/pwa/package.json
packages/react/package.json
yarn.lock

* **core:** deduplicate mixins in config ([6287ae4](https://github.com/untool/untool/commit/6287ae4))

fix: upgrade untool

---

packages/spec/helpers/env.js

Until our dependencies got rid of deprecated lifecycle methods in their code, we have to ignore React's lifecycle warnings in our tests.
This change might become obsolete with the upgrade to Apollo v3.

chore(spec): ignore React lifecycle warnings in tests

---

packages/postcss/mixin.core.js
packages/postcss/package.json
yarn.lock

BREAKING CHANGE: Check the breaking changes in css-loader v2 and v3

feat(postcss): upgrade to css-loader v3

---

packages/jest-preset/jest-preset.js

see [`jest-config#Defaults`](https://github.com/facebook/jest/blob/v24.9.0/packages/jest-config/src/Defaults.ts#L45)

chore(jest-preset): remove tsx? file extensions

---

DEPRECATIONS.md
packages/config/package.json
packages/express/mixin.core.js
packages/express/package.json
packages/graphql/package.json
packages/hops/package.json
packages/hops/preset.js
packages/jest-preset/transforms/babel.js
packages/lambda/package.json
packages/mixin/package.json
packages/pwa/package.json
packages/react/package.json
yarn.lock

~~**Beware**: Wait for [untool#464](https://github.com/untool/untool/pull/464) to be merged & released before merging this PR!~~

Deprecate hops-express package

---

packages/graphql/preset.js

fix(graphql): add graphqlUri to browser whitelist

---

package.json

chore: update contributors list

---

packages/spec/package.json
yarn.lock

chore(spec): update Puppeteer to v2

---

lerna.json

in order to make it easier to align all Hops dependencies.
https://github.com/lerna/lerna/tree/master/commands/version#--force-publish

[RFC] chore: force-publish all packages

---

package.json

Let preinstall run on win32 systems

fix: update script to be platform neutral

---

packages/jest-preset/package.json
packages/react/package.json
yarn.lock

update babel packages to v7.7

---

packages/apollo-mock-server/package.json
packages/config/package.json
packages/hops/package.json
packages/lambda/package.json
packages/mixin/package.json
packages/pwa/package.json
packages/react-apollo/package.json
packages/react/package.json
yarn.lock

fix: upgrade untool to 2.0.0-beta.0

---

packages/react/config/mixin.runtime.js

...when it's retrieved in the browser runtime.

feat(react): warn on non-whitelisted config property

---

.travis.yml

For reference: https://github.com/untool/untool/pull/527

Align travis configs

---

renovate.json

chore: allow renovate to update release branches

---

DOCUMENTATION.md

Configuration table syntax fix

---

.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
bors.toml
package.json
renovate.json
yarn.lock

Prepare next v11 release

---

package.json
yarn.lock

chore: update canarist

---

.travis.yml

chore: do not run travis on branches ending in ".tmp"

---

.travis.yml
package.json
packages/react/config/mixin.runtime.js
packages/redux/action-creator-dispatcher/mixin.runtime-common.js
packages/spec/integration/redux/__tests__/develop.js
packages/spec/integration/redux/index.js
yarn.lock

Release v12

---

packages/webpack/lib/configs/build.js
packages/webpack/lib/configs/develop.js
packages/webpack/lib/configs/node.js
packages/webpack/lib/middlewares/render.js
packages/webpack/lib/middlewares/stats.js
packages/webpack/lib/plugins/log.js
packages/webpack/lib/plugins/render.js
packages/webpack/lib/plugins/stats.js
packages/webpack/lib/shims/develop.js
packages/webpack/lib/shims/node.js
packages/webpack/lib/utils/compiler.js
packages/webpack/lib/utils/errors.js
packages/webpack/lib/utils/loader.js
packages/webpack/lib/utils/modules.js
packages/webpack/mixins/build/mixin.core.js
packages/webpack/mixins/config/mixin.core.js
packages/webpack/mixins/develop/mixin.core.js
packages/webpack/mixins/render/mixin.core.js
packages/webpack/mixins/start/mixin.core.js
packages/webpack/mixins/stats/mixin.core.js

refactor: restructure hops-webpack

---

DOCUMENTATION.md
packages/webpack/README.md
packages/yargs/README.md

docs: use relative links

---

packages/redux/action-creator-dispatcher/mixin.runtime-common.js

fix(redux): packages must only contain syntactically valid ES5/ES6

---

packages/bootstrap/index.js
packages/bootstrap/package.json
packages/express/mixins/mixin.core.js
packages/express/package.json
packages/info/doctor/index.js
packages/info/doctor/mixin.core.js
packages/info/package.json
packages/mixin/package.json
packages/react/package.json
packages/react/render/mixin.browser.js
packages/react/render/mixin.server.js
packages/webpack/package.json
packages/yargs/package.json
yarn.lock

fix: upgrade to mixinable@5

---

packages/bootstrap/index.js
packages/bootstrap/package.json
packages/express/mixins/mixin.core.js
packages/express/package.json
packages/info/doctor/index.js
packages/info/doctor/mixin.core.js
packages/info/package.json
packages/mixin/package.json
packages/react/package.json
packages/react/render/mixin.browser.js
packages/react/render/mixin.server.js
packages/webpack/package.json
packages/yargs/package.json
yarn.lock

fix: upgrade to mixinable v5

---

packages/express/mixins/mixin.core.js
packages/webpack/lib/plugins/stats.js

Cherry-pick v12 commits for next release

---

packages/react/import-component/babel.js
packages/react/lib/resource-hints.js
packages/react/lib/template.js
packages/react/render/mixin.server.js
packages/spec/integration/react/__tests__/develop.js
packages/spec/integration/react/bold-text.js
packages/spec/integration/react/index.js
packages/webpack/lib/plugins/stats.js

feat: Enable Resource Hints

---

packages/info/doctor/validators/duplicates.js
packages/info/package.json
packages/react/package.json
packages/webpack/package.json
yarn.lock

fix: update duplitect

---

.prettierignore
packages/webpack/mixins/build/mixin.core.js
packages/webpack/package.json
yarn.lock

~~I added the temporary commit [`84a7788`](https://github.com/xing/hops/pull/1224/commits/84a778856f58305b80194d01ceb6ca13ac99beb6), so it's possible to check out the message. Just run…~~
```
$ (cd packages/spec/integration/react/ && ../../../../node_modules/.bin/hops start)
$ (cd packages/spec/integration/react/ && ../../../../node_modules/.bin/hops build)
```
~~…in your terminal and witness its beauty. :p~~
<details>
| …

feat(webpack): improve feedback on conflicting core-js versions

---

packages/webpack/lib/plugins/log.js

feat(webpack): print total bundle size

---

DOCUMENTATION.md
packages/webpack/README.md
packages/webpack/lib/configs/node.js
packages/webpack/lib/shims/node.js
packages/webpack/mixins/fast-dev/mixin.core.js
packages/webpack/mixins/optimizations/mixin.core.js
packages/webpack/package.json
packages/webpack/preset.js

feat(webpack): introduce experimental fast-build mode

---

.prettierignore
packages/webpack/mixins/build/mixin.core.js

picks #1266 & #1267
<details>
| --- | --- |
| bors delegate=[list] | Allow the listed users to r+ this …

Pick #1266 & #1267

---

packages/apollo-mock-server/mixin.core.js
packages/spec/helpers/env.js
packages/spec/integration/lambda/__tests__/build.js
packages/spec/integration/postcss/__tests__/build.js
packages/spec/integration/react/index.js
packages/webpack/README.md
packages/webpack/index.js
packages/webpack/lib/middlewares/render.js
packages/webpack/lib/middlewares/stats.js
packages/webpack/lib/plugins/stats.js
packages/webpack/lib/utils/compiler-fork.js
packages/webpack/lib/utils/compiler.js
packages/webpack/mixins/build/mixin.core.js
packages/webpack/mixins/develop/mixin.core.js
packages/webpack/mixins/render/mixin.core.js
packages/webpack/mixins/stats/mixin.core.js
packages/webpack/package.json
yarn.lock

feat(webpack): introduce parallel build (v12.x)

---

packages/apollo-mock-server/mixin.core.js
packages/bootstrap/lib/config.js
packages/bootstrap/lib/loader.js
packages/config/index.js
packages/hops/bin.js
packages/info/README.md
packages/react/import-component/babel.js
packages/webpack/lib/configs/build.js
packages/webpack/lib/configs/develop.js
packages/webpack/lib/configs/node.js

Remove all last remnants of "untool"

---

packages/webpack/lib/utils/compiler-fork.js
packages/webpack/lib/utils/compiler.js
packages/webpack/lib/utils/errors.js
packages/webpack/package.json

fix(webpack): replace serialize-error with a custom implementation (v12.x)

---

packages/webpack/lib/utils/errors.js
yarn.lock

Fix-up for #1352

---

packages/webpack/lib/utils/errors.js
yarn.lock

Fix-up for #1352 (v12.x)

---

packages/webpack/lib/utils/errors.js

chore: correct error name for deserialization (v12.x)

---

packages/spec/integration/typescript-styled-components/__tests__/develop.js
packages/spec/integration/typescript-styled-components/index.tsx
packages/spec/integration/typescript-styled-components/package.json
packages/spec/integration/typescript-styled-components/tsconfig.json
packages/typescript/mixin.core.js
packages/typescript/tsconfig.json

<details>
| --- | --- |
| bors …

fix(typescript): preserve JSX when styled-components are present

---

packages/webpack/lib/utils/errors.js

fix(webpack): accept object argument in BuildError (v13.x)

---

packages/webpack/lib/utils/errors.js

fix(webpack): accept object argument in BuildError (v12.x)

---

packages/bootstrap/package.json
packages/create-hops-app/package.json
packages/express/package.json
packages/graphql/package.json
packages/hops/package.json
packages/jest-preset/package.json
packages/mixin/package.json
packages/react-apollo/package.json
packages/react/package.json
packages/redux/package.json
packages/spec/integration/hops/package.json
packages/spec/integration/typescript-unit-testing/package.json
packages/spec/package.json
packages/styled-components/package.json
packages/template-graphql/package.json
packages/template-react/package.json
packages/template-redux/package.json
packages/webpack/lib/configs/develop.js
packages/webpack/mixins/develop/mixin.core.js
packages/webpack/package.json
packages/yargs/package.json
yarn.lock

This PR upgrades several dependencies at once.
<details>
| --- | --- | …

Upgrade dependencies

---

packages/bootstrap/package.json
packages/create-hops-app/package.json
packages/express/package.json
packages/graphql/package.json
packages/hops/package.json
packages/jest-preset/package.json
packages/mixin/package.json
packages/react-apollo/package.json
packages/react/package.json
packages/redux/package.json
packages/spec/package.json
packages/styled-components/package.json
packages/template-graphql/package.json
packages/template-react/package.json
packages/template-redux/package.json
packages/webpack/lib/configs/develop.js
packages/webpack/mixins/develop/mixin.core.js
packages/webpack/package.json
packages/yargs/package.json
yarn.lock

This pull request updates several dependencies at once.
<details>
| --- | --- |
| bors delegate=[list] | …

Upgrade dependencies v13

---

packages/webpack/mixins/optimizations/mixin.core.js

There have been a few bugs and sources of confusion in the current
implementation of the optimizations mixin, therefore I decided to
refactor it in order to improve readability.
<details>
| --- | --- |
| bors …

refactor(webpack): clean-up optimizations mixin

---

packages/spec/integration/typescript-styled-components/index.tsx
packages/spec/integration/typescript-styled-components/package.json
packages/spec/package.json
yarn.lock

...instead of failing with error message:
```
[tsl] ERROR in ./packages/spec/integration/typescript-styled-components/index.tsx(13,7)
TS2322: Type '{ children: string; css: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>'.
Property 'css' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>'.
```
<details>
| --- | --- …

chore(spec): make TS/styled-components example build

---

.github/workflows/node-ci.yml
package.json
yarn.lock

Introduce canarist projects

---

.github/workflows/node-ci.yml
package.json
yarn.lock

picks #1452 
<details>
| --- | --- | …

Introduce canarist projects (v13)

---

.github/workflows/node-ci.yml
package.json
yarn.lock

picks #1452 
Let's see, whether the canarist test on the kicker-trainer actually runs successfully… 😬 
<details>
| --- | --- |
| bors delegate+ | Allow the pull request author to …

Introduce canarist projects (v12)

---

packages/react-apollo/README.md

docs(react-apollo): describe importing queries in Typescript projects

---

.github/workflows/codeql-analysis.yml

chore: enable codeql for security analysis

---

packages/webpack/lib/utils/compiler-fork.js
packages/webpack/lib/utils/compiler.js

Prepare next v12.x release

---

.github/workflows/codeql-analysis.yml
.github/workflows/node-ci.yml
.prettierignore
CODE_OF_CONDUCT.md
package.json
packages/development-proxy/README.md
packages/express/README.md
packages/lambda/cloudformation.yaml

chore: check code formatting in CI

---

.github/workflows/codeql-analysis.yml
.github/workflows/node-ci.yml
.prettierignore
CODE_OF_CONDUCT.md
package.json
packages/development-proxy/README.md
packages/express/README.md
packages/jest-environment/helpers.js
packages/lambda/cloudformation.yaml
packages/postcss/mixin.core.js
packages/spec/package.json

Prepare next v13.x release

---

LICENSE.txt

docs: update year in license

---

LICENSE.txt
packages/jest-environment/README.md

Release v13.x

---

.github/workflows/node-ci.yml
.prettierignore
CODE_OF_CONDUCT.md
LICENSE.txt
package.json
packages/development-proxy/README.md
packages/express/README.md
packages/lambda/cloudformation.yaml
packages/template-graphql/src/home/commits.gql

Release v12.x

---

test.txt

chore: test more

---

bors.toml

chore: add status placeholder for every required check

---

.github/workflows/publish.yml

chore: fetch more commits, so we are able to get the correct diff

---

lerna.json

chore: set correct npm release tag

---

packages/react/config/context.js
packages/react/import-component/context.js
packages/react/server-data/context.js

...in order to improve their findability in the component panel of the
React Dev Tools.
<details>
| --- | --- |
| bors delegate+ | Allow the pull request author to merge their …

feat: provide display names to Hops's React contexts

---

package.json

chore: fix prerelease command

---

lerna.json

chore: update npm dist-tag on v13.x release branch

---

.github/check-label.yml
.github/release-bot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/publish.yml
README.md
renovate.json

Prepare v14 release

---

packages/create-hops-app/package.json

fix(create-hops-app): rename bin to "create-hops-app" for stable version

---

package.json

chore: update canarist config for workshop (v13)

---

package.json

chore: update canarist config for workshop (v14)

---

package.json

chore: update canarist config for workshop (master)

---

DOCUMENTATION.md
packages/postcss/package.json
packages/pwa/package.json
packages/react/fast-refresh/mixin.core.js
packages/react/package.json
packages/react/preset.js
packages/spec/integration/fast-refresh/__tests__/develop.js
packages/spec/integration/fast-refresh/heading.js
packages/spec/integration/fast-refresh/index.js
packages/spec/integration/fast-refresh/package.json
packages/template-react/src/counter/index.jsx
packages/webpack/package.json
yarn.lock

replaces #1408 
<details>
| --- | --- | …

feat(webpack): add fast refresh plugin

---

packages/spec/integration/fast-refresh/package.json

chore(spec): fix display name

---

packages/webpack/README.md

Known drawbacks and limitations of esbuild have been documented.
<details>
| --- | --- |
| bors …

docs(webpack): document known drawbacks and limitations of esbuild

---

renovate.json

follow-up of #1784
<details>
| --- | --- | …

chore: preserve semver ranges

---

DOCUMENTATION.md
packages/react/README.md
packages/react/build/mixin.core.js
packages/spec/integration/react/bold-text.js
packages/spec/integration/typescript/content.tsx
packages/webpack/README.md

feat: enable jsx transform

---

packages/webpack/lib/configs/develop.js
packages/webpack/lib/plugins/stats.js

fix: webpack adjustments

---

packages/template-graphql/src/home/index.jsx
packages/template-graphql/src/home/spec/index.spec.jsx

fix(template-graphql): correctly pass data and loading state

---

package.json
packages/jest-preset/jest-preset.js
packages/jest-preset/package.json
packages/jest-preset/setup-msw.js
packages/msw/CHANGELOG.md
packages/msw/README.md
packages/msw/integration.d.ts
packages/msw/integration.js
packages/msw/mixin.browser.js
packages/msw/mixin.core.js
packages/msw/package.json
packages/msw/preset.js
packages/msw/unit.d.ts
packages/msw/unit.js
packages/react-apollo/index.js
packages/spec/integration/redux/__tests__/mocked.js
packages/spec/integration/redux/index.js
packages/spec/integration/redux/package.json
packages/template-graphql/package.json
packages/template-graphql/src/home/spec/__snapshots__/index.spec.jsx.snap
packages/template-graphql/src/home/spec/index.spec.jsx
yarn.lock

feat: add hops-msw package

---

DOCUMENTATION.md

docs: elaborate on Node version declarations

---

packages/msw/mixin.browser.js

fix(msw): delay rendering until msw mocks have been registered

---

packages/msw/index.d.ts
packages/msw/mixin.browser.js
packages/msw/mixin.core.js
packages/msw/mixin.server.js
packages/msw/package.json

Misc fixes for msw

---

packages/express/lib/serve.js

errors thrown in async middlewares would usually lead to
unhandled promise rejections and wouldn't trigger the express
error handler.
this change catches exceptions in async middlewares and forwards
them to the express error handler by calling `next`
Co-authored-by: Björn Brauer <bjoern.brauer@new-work.se>
Co-authored-by: Jonas Holland <jonas.holland@new-work.se>
<details>
| Syntax | …

feat: handle errors in async middlewares

---

.github/check-label.yml
.github/release-bot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/publish.yml
README.md
renovate.json

This prepares the hops 15 release
- needs a 15.x release branch
- 
<details>
| --- | --- |
| bors …

Prepare v15 release

---

package.json
packages/jest-environment/index.js
packages/jest-environment/package.json
packages/jest-preset/jest-preset.js
packages/jest-preset/package.json
packages/lambda/lib/prompt.js
packages/lambda/package.json
yarn.lock

Remove colors

---

packages/styled-components/package.json
yarn.lock

Lock file maintenance

---

package.json

<details>
| --- | --- |
| bors …

fix: remove resolution for msw
